package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.ActivityDealer;

public interface ActivityDealerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_dealer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_dealer
     *
     * @mbggenerated
     */
    int insert(ActivityDealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_dealer
     *
     * @mbggenerated
     */
    int insertSelective(ActivityDealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_dealer
     *
     * @mbggenerated
     */
    ActivityDealer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_dealer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ActivityDealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_dealer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ActivityDealer record);
}