package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.ActivityTag;

public interface ActivityTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_tag
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_tag
     *
     * @mbggenerated
     */
    int insert(ActivityTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_tag
     *
     * @mbggenerated
     */
    int insertSelective(ActivityTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_tag
     *
     * @mbggenerated
     */
    ActivityTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ActivityTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ActivityTag record);
}