package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.ActivityLink;

public interface ActivityLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_link
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_link
     *
     * @mbggenerated
     */
    int insert(ActivityLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_link
     *
     * @mbggenerated
     */
    int insertSelective(ActivityLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_link
     *
     * @mbggenerated
     */
    ActivityLink selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_link
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ActivityLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_link
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ActivityLink record);
}