package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.ActivityChannel;

import java.util.List;

public interface ActivityChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_channel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_channel
     *
     * @mbggenerated
     */
    int insert(ActivityChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_channel
     *
     * @mbggenerated
     */
    int insertSelective(ActivityChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_channel
     *
     * @mbggenerated
     */
    ActivityChannel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_channel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ActivityChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_channel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ActivityChannel record);
    //对活动渠道进行全查(maxing)
    public List<ActivityChannel> selectActivityChannels();
}