package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.ActivityCar;

public interface ActivityCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_car
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_car
     *
     * @mbggenerated
     */
    int insert(ActivityCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_car
     *
     * @mbggenerated
     */
    int insertSelective(ActivityCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_car
     *
     * @mbggenerated
     */
    ActivityCar selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ActivityCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ActivityCar record);
}