package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.ActivityInterface;

public interface ActivityInterfaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_interface
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_interface
     *
     * @mbggenerated
     */
    int insert(ActivityInterface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_interface
     *
     * @mbggenerated
     */
    int insertSelective(ActivityInterface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_interface
     *
     * @mbggenerated
     */
    ActivityInterface selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_interface
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ActivityInterface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_interface
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ActivityInterface record);
}