package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.Activity;
import com.qf.withmycar.pojo.ActivityCategory;
import com.qf.withmycar.pojo.ActivityState;

import java.util.List;

public interface ActivityListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_category
     *
     * @mbggenerated
     */
    int insert(ActivityCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_category
     *
     * @mbggenerated
     */
    int insertSelective(ActivityCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_category
     *
     * @mbggenerated
     */
    ActivityCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ActivityCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ActivityCategory record);
    //maxing
    public List<ActivityCategory> selectActivityCategorys();
    public List<ActivityState> selectActivityStates();
    public List<ActivityCategory> selectActivityCategoryLike(String name);//活动类型模糊查询
    public ActivityCategory selectActivityCategoryByName(String name);
}