package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.AdminRoleMenuKey;

import java.util.List;

public interface AdminRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(AdminRoleMenuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_menu
     *
     * @mbggenerated
     */
    int insert(AdminRoleMenuKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_menu
     *
     * @mbggenerated
     */
    int insertSelective(AdminRoleMenuKey record);

}