package com.qf.withmycar.mapper;

import com.qf.withmycar.dto.AdminMenuAuthDto;
import com.qf.withmycar.pojo.AdminRole;
import com.qf.withmycar.pojo.AdminRoleMenuKey;

import java.util.List;

public interface AdminRoleMapper {

    /**
     *增加权限
     */
    public void insertAdminRoleMenu(AdminRoleMenuKey adminRoleMenuKey);
    /**
     * 查询新角色id
     */
    public int selectAdminRoleId(String name);

    /**
     * 添加新角色
     */
    public void insertAdminRole(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated
     */
    int insert(AdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated
     */
    int insertSelective(AdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated
     */
    AdminRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdminRole record);


    /*
    查询
    */
    public List<AdminRole> selectAdminRoleOne();

    /*
    改删
    */
    public void updateRoleDeleted(int id);
    public void deleteRole(int id);

     /*
    编辑角色权限
    */
     public boolean deleteRoleAuth(int id);
     public void insertRoleAuth(AdminRoleMenuKey adminRoleMenuKey);

    //模糊
    public List<AdminRole> mohuchaxun(String mohu);


}