package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.ArticleAction;

public interface ArticleActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_action
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_action
     *
     * @mbggenerated
     */
    int insert(ArticleAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_action
     *
     * @mbggenerated
     */
    int insertSelective(ArticleAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_action
     *
     * @mbggenerated
     */
    ArticleAction selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_action
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ArticleAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_action
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ArticleAction record);
}