package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.CarImage;

public interface CarImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_image
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_image
     *
     * @mbggenerated
     */
    int insert(CarImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_image
     *
     * @mbggenerated
     */
    int insertSelective(CarImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_image
     *
     * @mbggenerated
     */
    CarImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CarImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CarImage record);
}