package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.CarModelImage;

public interface CarModelImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model_image
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model_image
     *
     * @mbggenerated
     */
    int insert(CarModelImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model_image
     *
     * @mbggenerated
     */
    int insertSelective(CarModelImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model_image
     *
     * @mbggenerated
     */
    CarModelImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CarModelImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CarModelImage record);
}