package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.CarModel;

public interface CarModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated
     */
    int insert(CarModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated
     */
    int insertSelective(CarModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated
     */
    CarModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CarModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_model
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CarModel record);
}