package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.CarMake;

public interface CarMakeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_make
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_make
     *
     * @mbggenerated
     */
    int insert(CarMake record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_make
     *
     * @mbggenerated
     */
    int insertSelective(CarMake record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_make
     *
     * @mbggenerated
     */
    CarMake selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_make
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CarMake record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_make
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CarMake record);
}