package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.CarSelectList;

public interface CarSelectListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_select_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_select_list
     *
     * @mbggenerated
     */
    int insert(CarSelectList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_select_list
     *
     * @mbggenerated
     */
    int insertSelective(CarSelectList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_select_list
     *
     * @mbggenerated
     */
    CarSelectList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_select_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CarSelectList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_select_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CarSelectList record);
}