package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.ChooseLog;

public interface ChooseLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choose_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choose_log
     *
     * @mbggenerated
     */
    int insert(ChooseLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choose_log
     *
     * @mbggenerated
     */
    int insertSelective(ChooseLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choose_log
     *
     * @mbggenerated
     */
    ChooseLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choose_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChooseLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choose_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChooseLog record);
}