package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.DictWeight;

public interface DictWeightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_weight
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_weight
     *
     * @mbggenerated
     */
    int insert(DictWeight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_weight
     *
     * @mbggenerated
     */
    int insertSelective(DictWeight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_weight
     *
     * @mbggenerated
     */
    DictWeight selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_weight
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DictWeight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_weight
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DictWeight record);
}