package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.AdminUser;
import com.qf.withmycar.pojo.MemberLoginLog;
import com.qf.withmycar.vo.MemberLoginLogUserVo;
import com.qf.withmycar.vo.MemberLoginLogVo;

import java.util.List;

public interface MemberLoginLogMapper {

    /**
     * 全查
     */

    public List<MemberLoginLog> memberAll();

    /**
     * 全查
     */

    public List<MemberLoginLogUserVo> selectMo(Integer id);

    /**
     * 个人中心资料查询
     */
    public List<MemberLoginLogVo> selectA(Integer id);

    /**
     * 修改
     */
    public void updateUser(AdminUser user);

    /**
     * 修改密码
     */
    public String updateUserPass(AdminUser user1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_login_log
     *
     * @mbggenerated
     */
    int delteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_login_log
     *
     * @mbggenerated
     */
    int insert(MemberLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_login_log
     *
     * @mbggenerated
     */
    int insertSelective(MemberLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_login_log
     *
     * @mbggenerated
     */
    MemberLoginLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_login_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemberLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_login_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemberLoginLog record);
}