package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.MemberTag;

public interface MemberTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tag
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tag
     *
     * @mbggenerated
     */
    int insert(MemberTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tag
     *
     * @mbggenerated
     */
    int insertSelective(MemberTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tag
     *
     * @mbggenerated
     */
    MemberTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemberTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemberTag record);
}