package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.MemberToken;

public interface MemberTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_token
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_token
     *
     * @mbggenerated
     */
    int insert(MemberToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_token
     *
     * @mbggenerated
     */
    int insertSelective(MemberToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_token
     *
     * @mbggenerated
     */
    MemberToken selectByPrimaryKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_token
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemberToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_token
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemberToken record);
}