package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.MessageSendlog;

public interface MessageSendlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_sendlog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_sendlog
     *
     * @mbggenerated
     */
    int insert(MessageSendlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_sendlog
     *
     * @mbggenerated
     */
    int insertSelective(MessageSendlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_sendlog
     *
     * @mbggenerated
     */
    MessageSendlog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_sendlog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MessageSendlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_sendlog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MessageSendlog record);
}