package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.ProductCarActivity;

public interface ProductCarActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_car_activity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_car_activity
     *
     * @mbggenerated
     */
    int insert(ProductCarActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_car_activity
     *
     * @mbggenerated
     */
    int insertSelective(ProductCarActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_car_activity
     *
     * @mbggenerated
     */
    ProductCarActivity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_car_activity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductCarActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_car_activity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductCarActivity record);
}