package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.SdkInterfaceParm;

public interface SdkInterfaceParmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_interface_parm
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_interface_parm
     *
     * @mbggenerated
     */
    int insert(SdkInterfaceParm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_interface_parm
     *
     * @mbggenerated
     */
    int insertSelective(SdkInterfaceParm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_interface_parm
     *
     * @mbggenerated
     */
    SdkInterfaceParm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_interface_parm
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkInterfaceParm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_interface_parm
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkInterfaceParm record);
}