package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.SdkInterfaceInfo;

public interface SdkInterfaceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_interface_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_interface_info
     *
     * @mbggenerated
     */
    int insert(SdkInterfaceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_interface_info
     *
     * @mbggenerated
     */
    int insertSelective(SdkInterfaceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_interface_info
     *
     * @mbggenerated
     */
    SdkInterfaceInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_interface_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkInterfaceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_interface_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkInterfaceInfo record);
}