package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.SdkInterfaceType;

public interface SdkInterfaceTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_interface_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_interface_type
     *
     * @mbggenerated
     */
    int insert(SdkInterfaceType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_interface_type
     *
     * @mbggenerated
     */
    int insertSelective(SdkInterfaceType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_interface_type
     *
     * @mbggenerated
     */
    SdkInterfaceType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_interface_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkInterfaceType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_interface_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkInterfaceType record);
}