package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.SdkInterfaceUdparm;

public interface SdkInterfaceUdparmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_interface_udparm
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_interface_udparm
     *
     * @mbggenerated
     */
    int insert(SdkInterfaceUdparm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_interface_udparm
     *
     * @mbggenerated
     */
    int insertSelective(SdkInterfaceUdparm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_interface_udparm
     *
     * @mbggenerated
     */
    SdkInterfaceUdparm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_interface_udparm
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SdkInterfaceUdparm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdk_interface_udparm
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SdkInterfaceUdparm record);
}