package com.qf.withmycar.mapper;

import com.qf.withmycar.pojo.VisitLog;

public interface VisitLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_log
     *
     * @mbggenerated
     */
    int insert(VisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_log
     *
     * @mbggenerated
     */
    int insertSelective(VisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_log
     *
     * @mbggenerated
     */
    VisitLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VisitLog record);
}