server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.12.151.233:3306/withmycars
    username: root
    password: 799681608
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: byf2075689@qq.com
    password: gmbefpcdxxvfbhgh
  #  thymeleaf:
  #    servlet:
  #      content-type: text/html
  #    cache: false
  #    mode: LEGACYHTML5
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qf.withmycar.pojo
