package com.qf.withmycar.pojo;

public class ActivityTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_tag.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_tag.activity_id
     *
     * @mbggenerated
     */
    private Long activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_tag.tag_id
     *
     * @mbggenerated
     */
    private Long tagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_tag.id
     *
     * @return the value of activity_tag.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_tag.id
     *
     * @param id the value for activity_tag.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_tag.activity_id
     *
     * @return the value of activity_tag.activity_id
     *
     * @mbggenerated
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_tag.activity_id
     *
     * @param activityId the value for activity_tag.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_tag.tag_id
     *
     * @return the value of activity_tag.tag_id
     *
     * @mbggenerated
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_tag.tag_id
     *
     * @param tagId the value for activity_tag.tag_id
     *
     * @mbggenerated
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }
}