package com.qf.withmycar.pojo;

public class ActivityInterface {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_interface.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_interface.activity_id
     *
     * @mbggenerated
     */
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_interface.interface_id
     *
     * @mbggenerated
     */
    private Integer interfaceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_interface.sdk_id
     *
     * @mbggenerated
     */
    private Integer sdkId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_interface.id
     *
     * @return the value of activity_interface.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_interface.id
     *
     * @param id the value for activity_interface.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_interface.activity_id
     *
     * @return the value of activity_interface.activity_id
     *
     * @mbggenerated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_interface.activity_id
     *
     * @param activityId the value for activity_interface.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_interface.interface_id
     *
     * @return the value of activity_interface.interface_id
     *
     * @mbggenerated
     */
    public Integer getInterfaceId() {
        return interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_interface.interface_id
     *
     * @param interfaceId the value for activity_interface.interface_id
     *
     * @mbggenerated
     */
    public void setInterfaceId(Integer interfaceId) {
        this.interfaceId = interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_interface.sdk_id
     *
     * @return the value of activity_interface.sdk_id
     *
     * @mbggenerated
     */
    public Integer getSdkId() {
        return sdkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_interface.sdk_id
     *
     * @param sdkId the value for activity_interface.sdk_id
     *
     * @mbggenerated
     */
    public void setSdkId(Integer sdkId) {
        this.sdkId = sdkId;
    }
}