package com.qf.withmycar.pojo;

public class ActivityCar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_car.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_car.activity_id
     *
     * @mbggenerated
     */
    private Long activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_car.car_id
     *
     * @mbggenerated
     */
    private Long carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_car.enable
     *
     * @mbggenerated
     */
    private Integer enable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_car.id
     *
     * @return the value of activity_car.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_car.id
     *
     * @param id the value for activity_car.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_car.activity_id
     *
     * @return the value of activity_car.activity_id
     *
     * @mbggenerated
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_car.activity_id
     *
     * @param activityId the value for activity_car.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_car.car_id
     *
     * @return the value of activity_car.car_id
     *
     * @mbggenerated
     */
    public Long getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_car.car_id
     *
     * @param carId the value for activity_car.car_id
     *
     * @mbggenerated
     */
    public void setCarId(Long carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_car.enable
     *
     * @return the value of activity_car.enable
     *
     * @mbggenerated
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_car.enable
     *
     * @param enable the value for activity_car.enable
     *
     * @mbggenerated
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }
}