package com.qf.withmycar.pojo;

public class ActivityDealer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_dealer.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_dealer.activity_id
     *
     * @mbggenerated
     */
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_dealer.dealer_id
     *
     * @mbggenerated
     */
    private Integer dealerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_dealer.dealer_province
     *
     * @mbggenerated
     */
    private String dealerProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_dealer.dealer_city
     *
     * @mbggenerated
     */
    private String dealerCity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_dealer.id
     *
     * @return the value of activity_dealer.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_dealer.id
     *
     * @param id the value for activity_dealer.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_dealer.activity_id
     *
     * @return the value of activity_dealer.activity_id
     *
     * @mbggenerated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_dealer.activity_id
     *
     * @param activityId the value for activity_dealer.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_dealer.dealer_id
     *
     * @return the value of activity_dealer.dealer_id
     *
     * @mbggenerated
     */
    public Integer getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_dealer.dealer_id
     *
     * @param dealerId the value for activity_dealer.dealer_id
     *
     * @mbggenerated
     */
    public void setDealerId(Integer dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_dealer.dealer_province
     *
     * @return the value of activity_dealer.dealer_province
     *
     * @mbggenerated
     */
    public String getDealerProvince() {
        return dealerProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_dealer.dealer_province
     *
     * @param dealerProvince the value for activity_dealer.dealer_province
     *
     * @mbggenerated
     */
    public void setDealerProvince(String dealerProvince) {
        this.dealerProvince = dealerProvince == null ? null : dealerProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_dealer.dealer_city
     *
     * @return the value of activity_dealer.dealer_city
     *
     * @mbggenerated
     */
    public String getDealerCity() {
        return dealerCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_dealer.dealer_city
     *
     * @param dealerCity the value for activity_dealer.dealer_city
     *
     * @mbggenerated
     */
    public void setDealerCity(String dealerCity) {
        this.dealerCity = dealerCity == null ? null : dealerCity.trim();
    }
}