package com.qf.withmycar.pojo;

public class Activity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.category_id
     *
     * @mbggenerated
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.state
     *
     * @mbggenerated
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.summary
     *
     * @mbggenerated
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.link
     *
     * @mbggenerated
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.begin_time
     *
     * @mbggenerated
     */
    private Integer beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.end_time
     *
     * @mbggenerated
     */
    private Integer endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.channel_top
     *
     * @mbggenerated
     */
    private Byte channelTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.home_top
     *
     * @mbggenerated
     */
    private Byte homeTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.pv_count
     *
     * @mbggenerated
     */
    private Integer pvCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.uv_count
     *
     * @mbggenerated
     */
    private Integer uvCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.up_count
     *
     * @mbggenerated
     */
    private Integer upCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.fav_count
     *
     * @mbggenerated
     */
    private Integer favCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.publish_state
     *
     * @mbggenerated
     */
    private Byte publishState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.create_uid
     *
     * @mbggenerated
     */
    private Integer createUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.unpublish_uname
     *
     * @mbggenerated
     */
    private String unpublishUname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.unpublish_time
     *
     * @mbggenerated
     */
    private String unpublishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.seo_keywords
     *
     * @mbggenerated
     */
    private String seoKeywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.sdk_path
     *
     * @mbggenerated
     */
    private String sdkPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.like_count
     *
     * @mbggenerated
     */
    private Integer likeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.share_count
     *
     * @mbggenerated
     */
    private Integer shareCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.view_count
     *
     * @mbggenerated
     */
    private Integer viewCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.tags
     *
     * @mbggenerated
     */
    private String tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.cover_pic
     *
     * @mbggenerated
     */
    private String coverPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.cars
     *
     * @mbggenerated
     */
    private String cars;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.sdk_id
     *
     * @mbggenerated
     */
    private Integer sdkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.sdk_title
     *
     * @mbggenerated
     */
    private String sdkTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.dealer
     *
     * @mbggenerated
     */
    private String dealer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.id
     *
     * @return the value of activity.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.id
     *
     * @param id the value for activity.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.title
     *
     * @return the value of activity.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.title
     *
     * @param title the value for activity.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.category_id
     *
     * @return the value of activity.category_id
     *
     * @mbggenerated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.category_id
     *
     * @param categoryId the value for activity.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.url
     *
     * @return the value of activity.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.url
     *
     * @param url the value for activity.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.state
     *
     * @return the value of activity.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.state
     *
     * @param state the value for activity.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.summary
     *
     * @return the value of activity.summary
     *
     * @mbggenerated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.summary
     *
     * @param summary the value for activity.summary
     *
     * @mbggenerated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.link
     *
     * @return the value of activity.link
     *
     * @mbggenerated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.link
     *
     * @param link the value for activity.link
     *
     * @mbggenerated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.begin_time
     *
     * @return the value of activity.begin_time
     *
     * @mbggenerated
     */
    public Integer getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.begin_time
     *
     * @param beginTime the value for activity.begin_time
     *
     * @mbggenerated
     */
    public void setBeginTime(Integer beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.end_time
     *
     * @return the value of activity.end_time
     *
     * @mbggenerated
     */
    public Integer getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.end_time
     *
     * @param endTime the value for activity.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Integer endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.channel_top
     *
     * @return the value of activity.channel_top
     *
     * @mbggenerated
     */
    public Byte getChannelTop() {
        return channelTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.channel_top
     *
     * @param channelTop the value for activity.channel_top
     *
     * @mbggenerated
     */
    public void setChannelTop(Byte channelTop) {
        this.channelTop = channelTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.home_top
     *
     * @return the value of activity.home_top
     *
     * @mbggenerated
     */
    public Byte getHomeTop() {
        return homeTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.home_top
     *
     * @param homeTop the value for activity.home_top
     *
     * @mbggenerated
     */
    public void setHomeTop(Byte homeTop) {
        this.homeTop = homeTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.pv_count
     *
     * @return the value of activity.pv_count
     *
     * @mbggenerated
     */
    public Integer getPvCount() {
        return pvCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.pv_count
     *
     * @param pvCount the value for activity.pv_count
     *
     * @mbggenerated
     */
    public void setPvCount(Integer pvCount) {
        this.pvCount = pvCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.uv_count
     *
     * @return the value of activity.uv_count
     *
     * @mbggenerated
     */
    public Integer getUvCount() {
        return uvCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.uv_count
     *
     * @param uvCount the value for activity.uv_count
     *
     * @mbggenerated
     */
    public void setUvCount(Integer uvCount) {
        this.uvCount = uvCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.up_count
     *
     * @return the value of activity.up_count
     *
     * @mbggenerated
     */
    public Integer getUpCount() {
        return upCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.up_count
     *
     * @param upCount the value for activity.up_count
     *
     * @mbggenerated
     */
    public void setUpCount(Integer upCount) {
        this.upCount = upCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.fav_count
     *
     * @return the value of activity.fav_count
     *
     * @mbggenerated
     */
    public Integer getFavCount() {
        return favCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.fav_count
     *
     * @param favCount the value for activity.fav_count
     *
     * @mbggenerated
     */
    public void setFavCount(Integer favCount) {
        this.favCount = favCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.publish_state
     *
     * @return the value of activity.publish_state
     *
     * @mbggenerated
     */
    public Byte getPublishState() {
        return publishState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.publish_state
     *
     * @param publishState the value for activity.publish_state
     *
     * @mbggenerated
     */
    public void setPublishState(Byte publishState) {
        this.publishState = publishState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.create_uid
     *
     * @return the value of activity.create_uid
     *
     * @mbggenerated
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.create_uid
     *
     * @param createUid the value for activity.create_uid
     *
     * @mbggenerated
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.create_time
     *
     * @return the value of activity.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.create_time
     *
     * @param createTime the value for activity.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.author
     *
     * @return the value of activity.author
     *
     * @mbggenerated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.author
     *
     * @param author the value for activity.author
     *
     * @mbggenerated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.unpublish_uname
     *
     * @return the value of activity.unpublish_uname
     *
     * @mbggenerated
     */
    public String getUnpublishUname() {
        return unpublishUname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.unpublish_uname
     *
     * @param unpublishUname the value for activity.unpublish_uname
     *
     * @mbggenerated
     */
    public void setUnpublishUname(String unpublishUname) {
        this.unpublishUname = unpublishUname == null ? null : unpublishUname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.unpublish_time
     *
     * @return the value of activity.unpublish_time
     *
     * @mbggenerated
     */
    public String getUnpublishTime() {
        return unpublishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.unpublish_time
     *
     * @param unpublishTime the value for activity.unpublish_time
     *
     * @mbggenerated
     */
    public void setUnpublishTime(String unpublishTime) {
        this.unpublishTime = unpublishTime == null ? null : unpublishTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.seo_keywords
     *
     * @return the value of activity.seo_keywords
     *
     * @mbggenerated
     */
    public String getSeoKeywords() {
        return seoKeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.seo_keywords
     *
     * @param seoKeywords the value for activity.seo_keywords
     *
     * @mbggenerated
     */
    public void setSeoKeywords(String seoKeywords) {
        this.seoKeywords = seoKeywords == null ? null : seoKeywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.sdk_path
     *
     * @return the value of activity.sdk_path
     *
     * @mbggenerated
     */
    public String getSdkPath() {
        return sdkPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.sdk_path
     *
     * @param sdkPath the value for activity.sdk_path
     *
     * @mbggenerated
     */
    public void setSdkPath(String sdkPath) {
        this.sdkPath = sdkPath == null ? null : sdkPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.like_count
     *
     * @return the value of activity.like_count
     *
     * @mbggenerated
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.like_count
     *
     * @param likeCount the value for activity.like_count
     *
     * @mbggenerated
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.share_count
     *
     * @return the value of activity.share_count
     *
     * @mbggenerated
     */
    public Integer getShareCount() {
        return shareCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.share_count
     *
     * @param shareCount the value for activity.share_count
     *
     * @mbggenerated
     */
    public void setShareCount(Integer shareCount) {
        this.shareCount = shareCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.view_count
     *
     * @return the value of activity.view_count
     *
     * @mbggenerated
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.view_count
     *
     * @param viewCount the value for activity.view_count
     *
     * @mbggenerated
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.tags
     *
     * @return the value of activity.tags
     *
     * @mbggenerated
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.tags
     *
     * @param tags the value for activity.tags
     *
     * @mbggenerated
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.cover_pic
     *
     * @return the value of activity.cover_pic
     *
     * @mbggenerated
     */
    public String getCoverPic() {
        return coverPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.cover_pic
     *
     * @param coverPic the value for activity.cover_pic
     *
     * @mbggenerated
     */
    public void setCoverPic(String coverPic) {
        this.coverPic = coverPic == null ? null : coverPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.cars
     *
     * @return the value of activity.cars
     *
     * @mbggenerated
     */
    public String getCars() {
        return cars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.cars
     *
     * @param cars the value for activity.cars
     *
     * @mbggenerated
     */
    public void setCars(String cars) {
        this.cars = cars == null ? null : cars.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.sdk_id
     *
     * @return the value of activity.sdk_id
     *
     * @mbggenerated
     */
    public Integer getSdkId() {
        return sdkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.sdk_id
     *
     * @param sdkId the value for activity.sdk_id
     *
     * @mbggenerated
     */
    public void setSdkId(Integer sdkId) {
        this.sdkId = sdkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.sdk_title
     *
     * @return the value of activity.sdk_title
     *
     * @mbggenerated
     */
    public String getSdkTitle() {
        return sdkTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.sdk_title
     *
     * @param sdkTitle the value for activity.sdk_title
     *
     * @mbggenerated
     */
    public void setSdkTitle(String sdkTitle) {
        this.sdkTitle = sdkTitle == null ? null : sdkTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.dealer
     *
     * @return the value of activity.dealer
     *
     * @mbggenerated
     */
    public String getDealer() {
        return dealer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.dealer
     *
     * @param dealer the value for activity.dealer
     *
     * @mbggenerated
     */
    public void setDealer(String dealer) {
        this.dealer = dealer == null ? null : dealer.trim();
    }
}