package com.qf.withmycar.pojo;

public class ActivityChannel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_channel.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_channel.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_channel.is_deleted
     *
     * @mbggenerated
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_channel.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_channel.last_update_time
     *
     * @mbggenerated
     */
    private Integer lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_channel.use_count
     *
     * @mbggenerated
     */
    private String useCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_channel.sign
     *
     * @mbggenerated
     */
    private String sign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_channel.id
     *
     * @return the value of activity_channel.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_channel.id
     *
     * @param id the value for activity_channel.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_channel.name
     *
     * @return the value of activity_channel.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_channel.name
     *
     * @param name the value for activity_channel.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_channel.is_deleted
     *
     * @return the value of activity_channel.is_deleted
     *
     * @mbggenerated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_channel.is_deleted
     *
     * @param isDeleted the value for activity_channel.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_channel.create_time
     *
     * @return the value of activity_channel.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_channel.create_time
     *
     * @param createTime the value for activity_channel.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_channel.last_update_time
     *
     * @return the value of activity_channel.last_update_time
     *
     * @mbggenerated
     */
    public Integer getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_channel.last_update_time
     *
     * @param lastUpdateTime the value for activity_channel.last_update_time
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Integer lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_channel.use_count
     *
     * @return the value of activity_channel.use_count
     *
     * @mbggenerated
     */
    public String getUseCount() {
        return useCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_channel.use_count
     *
     * @param useCount the value for activity_channel.use_count
     *
     * @mbggenerated
     */
    public void setUseCount(String useCount) {
        this.useCount = useCount == null ? null : useCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_channel.sign
     *
     * @return the value of activity_channel.sign
     *
     * @mbggenerated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_channel.sign
     *
     * @param sign the value for activity_channel.sign
     *
     * @mbggenerated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }
}