package com.qf.withmycar.pojo;

public class ActivityPdata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.activity_id
     *
     * @mbggenerated
     */
    private Long activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.member_id
     *
     * @mbggenerated
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.province
     *
     * @mbggenerated
     */
    private Integer province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.province_name
     *
     * @mbggenerated
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.city
     *
     * @mbggenerated
     */
    private Integer city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.city_name
     *
     * @mbggenerated
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.brand_id
     *
     * @mbggenerated
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.brand_name
     *
     * @mbggenerated
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.make_id
     *
     * @mbggenerated
     */
    private Integer makeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.make_name
     *
     * @mbggenerated
     */
    private String makeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.model_id
     *
     * @mbggenerated
     */
    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.model_name
     *
     * @mbggenerated
     */
    private String modelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.car_id
     *
     * @mbggenerated
     */
    private Integer carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.car_name
     *
     * @mbggenerated
     */
    private String carName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.dealer_id
     *
     * @mbggenerated
     */
    private Integer dealerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.channel_id
     *
     * @mbggenerated
     */
    private Integer channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.state
     *
     * @mbggenerated
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.state_update_uid
     *
     * @mbggenerated
     */
    private Integer stateUpdateUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.state_update_time
     *
     * @mbggenerated
     */
    private Integer stateUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.visitor_guid
     *
     * @mbggenerated
     */
    private String visitorGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.visit_ip
     *
     * @mbggenerated
     */
    private String visitIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.dealer_name
     *
     * @mbggenerated
     */
    private String dealerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_pdata.extend_data
     *
     * @mbggenerated
     */
    private String extendData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.id
     *
     * @return the value of activity_pdata.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.id
     *
     * @param id the value for activity_pdata.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.activity_id
     *
     * @return the value of activity_pdata.activity_id
     *
     * @mbggenerated
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.activity_id
     *
     * @param activityId the value for activity_pdata.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.member_id
     *
     * @return the value of activity_pdata.member_id
     *
     * @mbggenerated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.member_id
     *
     * @param memberId the value for activity_pdata.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.name
     *
     * @return the value of activity_pdata.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.name
     *
     * @param name the value for activity_pdata.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.mobile
     *
     * @return the value of activity_pdata.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.mobile
     *
     * @param mobile the value for activity_pdata.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.province
     *
     * @return the value of activity_pdata.province
     *
     * @mbggenerated
     */
    public Integer getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.province
     *
     * @param province the value for activity_pdata.province
     *
     * @mbggenerated
     */
    public void setProvince(Integer province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.province_name
     *
     * @return the value of activity_pdata.province_name
     *
     * @mbggenerated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.province_name
     *
     * @param provinceName the value for activity_pdata.province_name
     *
     * @mbggenerated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.city
     *
     * @return the value of activity_pdata.city
     *
     * @mbggenerated
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.city
     *
     * @param city the value for activity_pdata.city
     *
     * @mbggenerated
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.city_name
     *
     * @return the value of activity_pdata.city_name
     *
     * @mbggenerated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.city_name
     *
     * @param cityName the value for activity_pdata.city_name
     *
     * @mbggenerated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.remark
     *
     * @return the value of activity_pdata.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.remark
     *
     * @param remark the value for activity_pdata.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.create_time
     *
     * @return the value of activity_pdata.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.create_time
     *
     * @param createTime the value for activity_pdata.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.brand_id
     *
     * @return the value of activity_pdata.brand_id
     *
     * @mbggenerated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.brand_id
     *
     * @param brandId the value for activity_pdata.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.brand_name
     *
     * @return the value of activity_pdata.brand_name
     *
     * @mbggenerated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.brand_name
     *
     * @param brandName the value for activity_pdata.brand_name
     *
     * @mbggenerated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.make_id
     *
     * @return the value of activity_pdata.make_id
     *
     * @mbggenerated
     */
    public Integer getMakeId() {
        return makeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.make_id
     *
     * @param makeId the value for activity_pdata.make_id
     *
     * @mbggenerated
     */
    public void setMakeId(Integer makeId) {
        this.makeId = makeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.make_name
     *
     * @return the value of activity_pdata.make_name
     *
     * @mbggenerated
     */
    public String getMakeName() {
        return makeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.make_name
     *
     * @param makeName the value for activity_pdata.make_name
     *
     * @mbggenerated
     */
    public void setMakeName(String makeName) {
        this.makeName = makeName == null ? null : makeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.model_id
     *
     * @return the value of activity_pdata.model_id
     *
     * @mbggenerated
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.model_id
     *
     * @param modelId the value for activity_pdata.model_id
     *
     * @mbggenerated
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.model_name
     *
     * @return the value of activity_pdata.model_name
     *
     * @mbggenerated
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.model_name
     *
     * @param modelName the value for activity_pdata.model_name
     *
     * @mbggenerated
     */
    public void setModelName(String modelName) {
        this.modelName = modelName == null ? null : modelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.car_id
     *
     * @return the value of activity_pdata.car_id
     *
     * @mbggenerated
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.car_id
     *
     * @param carId the value for activity_pdata.car_id
     *
     * @mbggenerated
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.car_name
     *
     * @return the value of activity_pdata.car_name
     *
     * @mbggenerated
     */
    public String getCarName() {
        return carName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.car_name
     *
     * @param carName the value for activity_pdata.car_name
     *
     * @mbggenerated
     */
    public void setCarName(String carName) {
        this.carName = carName == null ? null : carName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.dealer_id
     *
     * @return the value of activity_pdata.dealer_id
     *
     * @mbggenerated
     */
    public Integer getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.dealer_id
     *
     * @param dealerId the value for activity_pdata.dealer_id
     *
     * @mbggenerated
     */
    public void setDealerId(Integer dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.channel_id
     *
     * @return the value of activity_pdata.channel_id
     *
     * @mbggenerated
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.channel_id
     *
     * @param channelId the value for activity_pdata.channel_id
     *
     * @mbggenerated
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.state
     *
     * @return the value of activity_pdata.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.state
     *
     * @param state the value for activity_pdata.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.state_update_uid
     *
     * @return the value of activity_pdata.state_update_uid
     *
     * @mbggenerated
     */
    public Integer getStateUpdateUid() {
        return stateUpdateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.state_update_uid
     *
     * @param stateUpdateUid the value for activity_pdata.state_update_uid
     *
     * @mbggenerated
     */
    public void setStateUpdateUid(Integer stateUpdateUid) {
        this.stateUpdateUid = stateUpdateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.state_update_time
     *
     * @return the value of activity_pdata.state_update_time
     *
     * @mbggenerated
     */
    public Integer getStateUpdateTime() {
        return stateUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.state_update_time
     *
     * @param stateUpdateTime the value for activity_pdata.state_update_time
     *
     * @mbggenerated
     */
    public void setStateUpdateTime(Integer stateUpdateTime) {
        this.stateUpdateTime = stateUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.visitor_guid
     *
     * @return the value of activity_pdata.visitor_guid
     *
     * @mbggenerated
     */
    public String getVisitorGuid() {
        return visitorGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.visitor_guid
     *
     * @param visitorGuid the value for activity_pdata.visitor_guid
     *
     * @mbggenerated
     */
    public void setVisitorGuid(String visitorGuid) {
        this.visitorGuid = visitorGuid == null ? null : visitorGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.visit_ip
     *
     * @return the value of activity_pdata.visit_ip
     *
     * @mbggenerated
     */
    public String getVisitIp() {
        return visitIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.visit_ip
     *
     * @param visitIp the value for activity_pdata.visit_ip
     *
     * @mbggenerated
     */
    public void setVisitIp(String visitIp) {
        this.visitIp = visitIp == null ? null : visitIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.dealer_name
     *
     * @return the value of activity_pdata.dealer_name
     *
     * @mbggenerated
     */
    public String getDealerName() {
        return dealerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.dealer_name
     *
     * @param dealerName the value for activity_pdata.dealer_name
     *
     * @mbggenerated
     */
    public void setDealerName(String dealerName) {
        this.dealerName = dealerName == null ? null : dealerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_pdata.extend_data
     *
     * @return the value of activity_pdata.extend_data
     *
     * @mbggenerated
     */
    public String getExtendData() {
        return extendData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_pdata.extend_data
     *
     * @param extendData the value for activity_pdata.extend_data
     *
     * @mbggenerated
     */
    public void setExtendData(String extendData) {
        this.extendData = extendData == null ? null : extendData.trim();
    }
}