package com.qf.withmycar.pojo;

public class AdminUser {

    private Integer id;
    private String username;
    private String password;
    private String name;
    private Integer is_super;
    private String salt;
    private String phone;
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.create_time
     *
     * @mbggenerated
     */
    private String create_time;

    public String getCreate_time(String create_time) {
        return this.create_time;
    }

    public void setCreate_time(String create_time) {
        this.create_time = create_time;
    }

    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.is_super
     *
     * @mbggenerated
     */
    private Byte isSuper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.consumer
     *
     * @mbggenerated
     */
    private String consumer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.dept
     *
     * @mbggenerated
     */
    private String dept;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getIs_super() {
        return is_super;
    }

    public void setIs_super(Integer is_super) {
        this.is_super = is_super;
    }

    public String getSalt() {
        return salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Byte getStatus() {
        return status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public Integer getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    public Byte getIsSuper() {
        return isSuper;
    }

    public void setIsSuper(Byte isSuper) {
        this.isSuper = isSuper;
    }

    public String getConsumer() {
        return consumer;
    }

    public void setConsumer(String consumer) {
        this.consumer = consumer;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getDept() {
        return dept;
    }

    public void setDept(String dept) {
        this.dept = dept;
    }

    @Override
    public String toString() {
        return "AdminUser{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", name='" + name + '\'' +
                ", is_super=" + is_super +
                ", salt='" + salt + '\'' +
                ", phone='" + phone + '\'' +
                ", email='" + email + '\'' +
                ", status=" + status +
                ", create_time=" + create_time +
                ", createTime=" + createTime +
                ", isSuper=" + isSuper +
                ", consumer='" + consumer + '\'' +
                ", remark='" + remark + '\'' +
                ", dept='" + dept + '\'' +
                '}';
    }
}