package com.qf.withmycar.pojo;

import java.math.BigDecimal;

public class CarModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.brand_id
     *
     * @mbggenerated
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.brand_name
     *
     * @mbggenerated
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.make_id
     *
     * @mbggenerated
     */
    private Integer makeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.make_name
     *
     * @mbggenerated
     */
    private String makeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.display_name
     *
     * @mbggenerated
     */
    private String displayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.other_name
     *
     * @mbggenerated
     */
    private String otherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.english_name
     *
     * @mbggenerated
     */
    private String englishName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.country_class
     *
     * @mbggenerated
     */
    private Integer countryClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.country_class_name
     *
     * @mbggenerated
     */
    private String countryClassName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.body_form
     *
     * @mbggenerated
     */
    private Integer bodyForm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.body_form_name
     *
     * @mbggenerated
     */
    private String bodyFormName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.price_low
     *
     * @mbggenerated
     */
    private BigDecimal priceLow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.price_high
     *
     * @mbggenerated
     */
    private BigDecimal priceHigh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.level_name
     *
     * @mbggenerated
     */
    private String levelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.level_second
     *
     * @mbggenerated
     */
    private Integer levelSecond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.level_second_name
     *
     * @mbggenerated
     */
    private String levelSecondName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.sale_status
     *
     * @mbggenerated
     */
    private Byte saleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.all_spell
     *
     * @mbggenerated
     */
    private String allSpell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.country_id
     *
     * @mbggenerated
     */
    private Integer countryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.country_name
     *
     * @mbggenerated
     */
    private String countryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.update_time
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model.sync_time
     *
     * @mbggenerated
     */
    private Integer syncTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.id
     *
     * @return the value of car_model.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.id
     *
     * @param id the value for car_model.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.brand_id
     *
     * @return the value of car_model.brand_id
     *
     * @mbggenerated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.brand_id
     *
     * @param brandId the value for car_model.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.brand_name
     *
     * @return the value of car_model.brand_name
     *
     * @mbggenerated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.brand_name
     *
     * @param brandName the value for car_model.brand_name
     *
     * @mbggenerated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.make_id
     *
     * @return the value of car_model.make_id
     *
     * @mbggenerated
     */
    public Integer getMakeId() {
        return makeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.make_id
     *
     * @param makeId the value for car_model.make_id
     *
     * @mbggenerated
     */
    public void setMakeId(Integer makeId) {
        this.makeId = makeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.make_name
     *
     * @return the value of car_model.make_name
     *
     * @mbggenerated
     */
    public String getMakeName() {
        return makeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.make_name
     *
     * @param makeName the value for car_model.make_name
     *
     * @mbggenerated
     */
    public void setMakeName(String makeName) {
        this.makeName = makeName == null ? null : makeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.name
     *
     * @return the value of car_model.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.name
     *
     * @param name the value for car_model.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.display_name
     *
     * @return the value of car_model.display_name
     *
     * @mbggenerated
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.display_name
     *
     * @param displayName the value for car_model.display_name
     *
     * @mbggenerated
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.other_name
     *
     * @return the value of car_model.other_name
     *
     * @mbggenerated
     */
    public String getOtherName() {
        return otherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.other_name
     *
     * @param otherName the value for car_model.other_name
     *
     * @mbggenerated
     */
    public void setOtherName(String otherName) {
        this.otherName = otherName == null ? null : otherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.english_name
     *
     * @return the value of car_model.english_name
     *
     * @mbggenerated
     */
    public String getEnglishName() {
        return englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.english_name
     *
     * @param englishName the value for car_model.english_name
     *
     * @mbggenerated
     */
    public void setEnglishName(String englishName) {
        this.englishName = englishName == null ? null : englishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.country_class
     *
     * @return the value of car_model.country_class
     *
     * @mbggenerated
     */
    public Integer getCountryClass() {
        return countryClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.country_class
     *
     * @param countryClass the value for car_model.country_class
     *
     * @mbggenerated
     */
    public void setCountryClass(Integer countryClass) {
        this.countryClass = countryClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.country_class_name
     *
     * @return the value of car_model.country_class_name
     *
     * @mbggenerated
     */
    public String getCountryClassName() {
        return countryClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.country_class_name
     *
     * @param countryClassName the value for car_model.country_class_name
     *
     * @mbggenerated
     */
    public void setCountryClassName(String countryClassName) {
        this.countryClassName = countryClassName == null ? null : countryClassName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.body_form
     *
     * @return the value of car_model.body_form
     *
     * @mbggenerated
     */
    public Integer getBodyForm() {
        return bodyForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.body_form
     *
     * @param bodyForm the value for car_model.body_form
     *
     * @mbggenerated
     */
    public void setBodyForm(Integer bodyForm) {
        this.bodyForm = bodyForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.body_form_name
     *
     * @return the value of car_model.body_form_name
     *
     * @mbggenerated
     */
    public String getBodyFormName() {
        return bodyFormName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.body_form_name
     *
     * @param bodyFormName the value for car_model.body_form_name
     *
     * @mbggenerated
     */
    public void setBodyFormName(String bodyFormName) {
        this.bodyFormName = bodyFormName == null ? null : bodyFormName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.price_low
     *
     * @return the value of car_model.price_low
     *
     * @mbggenerated
     */
    public BigDecimal getPriceLow() {
        return priceLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.price_low
     *
     * @param priceLow the value for car_model.price_low
     *
     * @mbggenerated
     */
    public void setPriceLow(BigDecimal priceLow) {
        this.priceLow = priceLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.price_high
     *
     * @return the value of car_model.price_high
     *
     * @mbggenerated
     */
    public BigDecimal getPriceHigh() {
        return priceHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.price_high
     *
     * @param priceHigh the value for car_model.price_high
     *
     * @mbggenerated
     */
    public void setPriceHigh(BigDecimal priceHigh) {
        this.priceHigh = priceHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.level
     *
     * @return the value of car_model.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.level
     *
     * @param level the value for car_model.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.level_name
     *
     * @return the value of car_model.level_name
     *
     * @mbggenerated
     */
    public String getLevelName() {
        return levelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.level_name
     *
     * @param levelName the value for car_model.level_name
     *
     * @mbggenerated
     */
    public void setLevelName(String levelName) {
        this.levelName = levelName == null ? null : levelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.level_second
     *
     * @return the value of car_model.level_second
     *
     * @mbggenerated
     */
    public Integer getLevelSecond() {
        return levelSecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.level_second
     *
     * @param levelSecond the value for car_model.level_second
     *
     * @mbggenerated
     */
    public void setLevelSecond(Integer levelSecond) {
        this.levelSecond = levelSecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.level_second_name
     *
     * @return the value of car_model.level_second_name
     *
     * @mbggenerated
     */
    public String getLevelSecondName() {
        return levelSecondName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.level_second_name
     *
     * @param levelSecondName the value for car_model.level_second_name
     *
     * @mbggenerated
     */
    public void setLevelSecondName(String levelSecondName) {
        this.levelSecondName = levelSecondName == null ? null : levelSecondName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.sale_status
     *
     * @return the value of car_model.sale_status
     *
     * @mbggenerated
     */
    public Byte getSaleStatus() {
        return saleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.sale_status
     *
     * @param saleStatus the value for car_model.sale_status
     *
     * @mbggenerated
     */
    public void setSaleStatus(Byte saleStatus) {
        this.saleStatus = saleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.all_spell
     *
     * @return the value of car_model.all_spell
     *
     * @mbggenerated
     */
    public String getAllSpell() {
        return allSpell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.all_spell
     *
     * @param allSpell the value for car_model.all_spell
     *
     * @mbggenerated
     */
    public void setAllSpell(String allSpell) {
        this.allSpell = allSpell == null ? null : allSpell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.country_id
     *
     * @return the value of car_model.country_id
     *
     * @mbggenerated
     */
    public Integer getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.country_id
     *
     * @param countryId the value for car_model.country_id
     *
     * @mbggenerated
     */
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.country_name
     *
     * @return the value of car_model.country_name
     *
     * @mbggenerated
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.country_name
     *
     * @param countryName the value for car_model.country_name
     *
     * @mbggenerated
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName == null ? null : countryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.create_time
     *
     * @return the value of car_model.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.create_time
     *
     * @param createTime the value for car_model.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.update_time
     *
     * @return the value of car_model.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.update_time
     *
     * @param updateTime the value for car_model.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model.sync_time
     *
     * @return the value of car_model.sync_time
     *
     * @mbggenerated
     */
    public Integer getSyncTime() {
        return syncTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model.sync_time
     *
     * @param syncTime the value for car_model.sync_time
     *
     * @mbggenerated
     */
    public void setSyncTime(Integer syncTime) {
        this.syncTime = syncTime;
    }
}