package com.qf.withmycar.pojo;

public class CarParamandclass {
    private Integer cpcid;//参数类型_参数
    private Integer pacid;//参数类型id
    private Integer paramid;//参数id
    private Integer cpcsortid;//排序id
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_paramandclass.cpcid
     *
     * @return the value of car_paramandclass.cpcid
     *
     * @mbggenerated
     */
    public Integer getCpcid() {
        return cpcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_paramandclass.cpcid
     *
     * @param cpcid the value for car_paramandclass.cpcid
     *
     * @mbggenerated
     */
    public void setCpcid(Integer cpcid) {
        this.cpcid = cpcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_paramandclass.pacid
     *
     * @return the value of car_paramandclass.pacid
     *
     * @mbggenerated
     */
    public Integer getPacid() {
        return pacid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_paramandclass.pacid
     *
     * @param pacid the value for car_paramandclass.pacid
     *
     * @mbggenerated
     */
    public void setPacid(Integer pacid) {
        this.pacid = pacid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_paramandclass.paramid
     *
     * @return the value of car_paramandclass.paramid
     *
     * @mbggenerated
     */
    public Integer getParamid() {
        return paramid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_paramandclass.paramid
     *
     * @param paramid the value for car_paramandclass.paramid
     *
     * @mbggenerated
     */
    public void setParamid(Integer paramid) {
        this.paramid = paramid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_paramandclass.cpcsortid
     *
     * @return the value of car_paramandclass.cpcsortid
     *
     * @mbggenerated
     */
    public Integer getCpcsortid() {
        return cpcsortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_paramandclass.cpcsortid
     *
     * @param cpcsortid the value for car_paramandclass.cpcsortid
     *
     * @mbggenerated
     */
    public void setCpcsortid(Integer cpcsortid) {
        this.cpcsortid = cpcsortid;
    }
}