package com.qf.withmycar.pojo;

public class CarSParamClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_s_param_class.carpcid
     *
     * @mbggenerated
     */
    private Integer carpcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_s_param_class.carid
     *
     * @mbggenerated
     */
    private Integer carid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_s_param_class.cpcid
     *
     * @mbggenerated
     */
    private Integer cpcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_s_param_class.carpcinfo
     *
     * @mbggenerated
     */
    private String carpcinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_s_param_class.carpcid
     *
     * @return the value of car_s_param_class.carpcid
     *
     * @mbggenerated
     */
    public Integer getCarpcid() {
        return carpcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_s_param_class.carpcid
     *
     * @param carpcid the value for car_s_param_class.carpcid
     *
     * @mbggenerated
     */
    public void setCarpcid(Integer carpcid) {
        this.carpcid = carpcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_s_param_class.carid
     *
     * @return the value of car_s_param_class.carid
     *
     * @mbggenerated
     */
    public Integer getCarid() {
        return carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_s_param_class.carid
     *
     * @param carid the value for car_s_param_class.carid
     *
     * @mbggenerated
     */
    public void setCarid(Integer carid) {
        this.carid = carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_s_param_class.cpcid
     *
     * @return the value of car_s_param_class.cpcid
     *
     * @mbggenerated
     */
    public Integer getCpcid() {
        return cpcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_s_param_class.cpcid
     *
     * @param cpcid the value for car_s_param_class.cpcid
     *
     * @mbggenerated
     */
    public void setCpcid(Integer cpcid) {
        this.cpcid = cpcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_s_param_class.carpcinfo
     *
     * @return the value of car_s_param_class.carpcinfo
     *
     * @mbggenerated
     */
    public String getCarpcinfo() {
        return carpcinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_s_param_class.carpcinfo
     *
     * @param carpcinfo the value for car_s_param_class.carpcinfo
     *
     * @mbggenerated
     */
    public void setCarpcinfo(String carpcinfo) {
        this.carpcinfo = carpcinfo == null ? null : carpcinfo.trim();
    }
}