package com.qf.withmycar.pojo;

public class CarType {

    private Integer tyid;
    private String tyname;
    private Integer typarentid;
    private Integer tysortid;




    public Integer getTyid() {
        return tyid;
    }
    public void setTyid(Integer tyid) {
        this.tyid = tyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.tyname
     *
     * @return the value of car_type.tyname
     *
     * @mbggenerated
     */
    public String getTyname() {
        return tyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.tyname
     *
     * @param tyname the value for car_type.tyname
     *
     * @mbggenerated
     */
    public void setTyname(String tyname) {
        this.tyname = tyname == null ? null : tyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.typarentid
     *
     * @return the value of car_type.typarentid
     *
     * @mbggenerated
     */
    public Integer getTyparentid() {
        return typarentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.typarentid
     *
     * @param typarentid the value for car_type.typarentid
     *
     * @mbggenerated
     */
    public void setTyparentid(Integer typarentid) {
        this.typarentid = typarentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_type.tysortid
     *
     * @return the value of car_type.tysortid
     *
     * @mbggenerated
     */
    public Integer getTysortid() {
        return tysortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_type.tysortid
     *
     * @param tysortid the value for car_type.tysortid
     *
     * @mbggenerated
     */
    public void setTysortid(Integer tysortid) {
        this.tysortid = tysortid;
    }
}