package com.qf.withmycar.pojo;

public class ChooseLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choose_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choose_log.member_id
     *
     * @mbggenerated
     */
    private String memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choose_log.user_country
     *
     * @mbggenerated
     */
    private Byte userCountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choose_log.user_space
     *
     * @mbggenerated
     */
    private String userSpace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choose_log.user_power
     *
     * @mbggenerated
     */
    private String userPower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choose_log.user_comfort
     *
     * @mbggenerated
     */
    private String userComfort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choose_log.user_safe
     *
     * @mbggenerated
     */
    private String userSafe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choose_log.user_cost
     *
     * @mbggenerated
     */
    private String userCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choose_log.user_min
     *
     * @mbggenerated
     */
    private String userMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choose_log.user_max
     *
     * @mbggenerated
     */
    private String userMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choose_log.user_ptime
     *
     * @mbggenerated
     */
    private String userPtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choose_log.user_car
     *
     * @mbggenerated
     */
    private String userCar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choose_log.choose_car
     *
     * @mbggenerated
     */
    private String chooseCar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choose_log.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choose_log.id
     *
     * @return the value of choose_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choose_log.id
     *
     * @param id the value for choose_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choose_log.member_id
     *
     * @return the value of choose_log.member_id
     *
     * @mbggenerated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choose_log.member_id
     *
     * @param memberId the value for choose_log.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choose_log.user_country
     *
     * @return the value of choose_log.user_country
     *
     * @mbggenerated
     */
    public Byte getUserCountry() {
        return userCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choose_log.user_country
     *
     * @param userCountry the value for choose_log.user_country
     *
     * @mbggenerated
     */
    public void setUserCountry(Byte userCountry) {
        this.userCountry = userCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choose_log.user_space
     *
     * @return the value of choose_log.user_space
     *
     * @mbggenerated
     */
    public String getUserSpace() {
        return userSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choose_log.user_space
     *
     * @param userSpace the value for choose_log.user_space
     *
     * @mbggenerated
     */
    public void setUserSpace(String userSpace) {
        this.userSpace = userSpace == null ? null : userSpace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choose_log.user_power
     *
     * @return the value of choose_log.user_power
     *
     * @mbggenerated
     */
    public String getUserPower() {
        return userPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choose_log.user_power
     *
     * @param userPower the value for choose_log.user_power
     *
     * @mbggenerated
     */
    public void setUserPower(String userPower) {
        this.userPower = userPower == null ? null : userPower.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choose_log.user_comfort
     *
     * @return the value of choose_log.user_comfort
     *
     * @mbggenerated
     */
    public String getUserComfort() {
        return userComfort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choose_log.user_comfort
     *
     * @param userComfort the value for choose_log.user_comfort
     *
     * @mbggenerated
     */
    public void setUserComfort(String userComfort) {
        this.userComfort = userComfort == null ? null : userComfort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choose_log.user_safe
     *
     * @return the value of choose_log.user_safe
     *
     * @mbggenerated
     */
    public String getUserSafe() {
        return userSafe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choose_log.user_safe
     *
     * @param userSafe the value for choose_log.user_safe
     *
     * @mbggenerated
     */
    public void setUserSafe(String userSafe) {
        this.userSafe = userSafe == null ? null : userSafe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choose_log.user_cost
     *
     * @return the value of choose_log.user_cost
     *
     * @mbggenerated
     */
    public String getUserCost() {
        return userCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choose_log.user_cost
     *
     * @param userCost the value for choose_log.user_cost
     *
     * @mbggenerated
     */
    public void setUserCost(String userCost) {
        this.userCost = userCost == null ? null : userCost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choose_log.user_min
     *
     * @return the value of choose_log.user_min
     *
     * @mbggenerated
     */
    public String getUserMin() {
        return userMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choose_log.user_min
     *
     * @param userMin the value for choose_log.user_min
     *
     * @mbggenerated
     */
    public void setUserMin(String userMin) {
        this.userMin = userMin == null ? null : userMin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choose_log.user_max
     *
     * @return the value of choose_log.user_max
     *
     * @mbggenerated
     */
    public String getUserMax() {
        return userMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choose_log.user_max
     *
     * @param userMax the value for choose_log.user_max
     *
     * @mbggenerated
     */
    public void setUserMax(String userMax) {
        this.userMax = userMax == null ? null : userMax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choose_log.user_ptime
     *
     * @return the value of choose_log.user_ptime
     *
     * @mbggenerated
     */
    public String getUserPtime() {
        return userPtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choose_log.user_ptime
     *
     * @param userPtime the value for choose_log.user_ptime
     *
     * @mbggenerated
     */
    public void setUserPtime(String userPtime) {
        this.userPtime = userPtime == null ? null : userPtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choose_log.user_car
     *
     * @return the value of choose_log.user_car
     *
     * @mbggenerated
     */
    public String getUserCar() {
        return userCar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choose_log.user_car
     *
     * @param userCar the value for choose_log.user_car
     *
     * @mbggenerated
     */
    public void setUserCar(String userCar) {
        this.userCar = userCar == null ? null : userCar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choose_log.choose_car
     *
     * @return the value of choose_log.choose_car
     *
     * @mbggenerated
     */
    public String getChooseCar() {
        return chooseCar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choose_log.choose_car
     *
     * @param chooseCar the value for choose_log.choose_car
     *
     * @mbggenerated
     */
    public void setChooseCar(String chooseCar) {
        this.chooseCar = chooseCar == null ? null : chooseCar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choose_log.create_time
     *
     * @return the value of choose_log.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choose_log.create_time
     *
     * @param createTime the value for choose_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }
}