package com.qf.withmycar.pojo;

public class MemberFav {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_fav.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_fav.member_id
     *
     * @mbggenerated
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_fav.fav_type
     *
     * @mbggenerated
     */
    private Byte favType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_fav.content_id
     *
     * @mbggenerated
     */
    private Long contentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_fav.fav_time
     *
     * @mbggenerated
     */
    private Integer favTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_fav.fav_ip
     *
     * @mbggenerated
     */
    private String favIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_fav.id
     *
     * @return the value of member_fav.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_fav.id
     *
     * @param id the value for member_fav.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_fav.member_id
     *
     * @return the value of member_fav.member_id
     *
     * @mbggenerated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_fav.member_id
     *
     * @param memberId the value for member_fav.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_fav.fav_type
     *
     * @return the value of member_fav.fav_type
     *
     * @mbggenerated
     */
    public Byte getFavType() {
        return favType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_fav.fav_type
     *
     * @param favType the value for member_fav.fav_type
     *
     * @mbggenerated
     */
    public void setFavType(Byte favType) {
        this.favType = favType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_fav.content_id
     *
     * @return the value of member_fav.content_id
     *
     * @mbggenerated
     */
    public Long getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_fav.content_id
     *
     * @param contentId the value for member_fav.content_id
     *
     * @mbggenerated
     */
    public void setContentId(Long contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_fav.fav_time
     *
     * @return the value of member_fav.fav_time
     *
     * @mbggenerated
     */
    public Integer getFavTime() {
        return favTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_fav.fav_time
     *
     * @param favTime the value for member_fav.fav_time
     *
     * @mbggenerated
     */
    public void setFavTime(Integer favTime) {
        this.favTime = favTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_fav.fav_ip
     *
     * @return the value of member_fav.fav_ip
     *
     * @mbggenerated
     */
    public String getFavIp() {
        return favIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_fav.fav_ip
     *
     * @param favIp the value for member_fav.fav_ip
     *
     * @mbggenerated
     */
    public void setFavIp(String favIp) {
        this.favIp = favIp == null ? null : favIp.trim();
    }
}