package com.qf.withmycar.pojo;

public class MemberProfileLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile_log.member_id
     *
     * @mbggenerated
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile_log.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile_log.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile_log.gender
     *
     * @mbggenerated
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile_log.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile_log.avatar_url
     *
     * @mbggenerated
     */
    private String avatarUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile_log.mobile_code
     *
     * @mbggenerated
     */
    private String mobileCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile_log.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile_log.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile_log.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile_log.country
     *
     * @mbggenerated
     */
    private Integer country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile_log.province
     *
     * @mbggenerated
     */
    private Integer province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile_log.city
     *
     * @mbggenerated
     */
    private Integer city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile_log.district
     *
     * @mbggenerated
     */
    private Integer district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile_log.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile_log.register_time
     *
     * @mbggenerated
     */
    private Integer registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_profile_log.update_time
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile_log.id
     *
     * @return the value of member_profile_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile_log.id
     *
     * @param id the value for member_profile_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile_log.member_id
     *
     * @return the value of member_profile_log.member_id
     *
     * @mbggenerated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile_log.member_id
     *
     * @param memberId the value for member_profile_log.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile_log.nickname
     *
     * @return the value of member_profile_log.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile_log.nickname
     *
     * @param nickname the value for member_profile_log.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile_log.name
     *
     * @return the value of member_profile_log.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile_log.name
     *
     * @param name the value for member_profile_log.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile_log.gender
     *
     * @return the value of member_profile_log.gender
     *
     * @mbggenerated
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile_log.gender
     *
     * @param gender the value for member_profile_log.gender
     *
     * @mbggenerated
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile_log.level
     *
     * @return the value of member_profile_log.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile_log.level
     *
     * @param level the value for member_profile_log.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile_log.avatar_url
     *
     * @return the value of member_profile_log.avatar_url
     *
     * @mbggenerated
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile_log.avatar_url
     *
     * @param avatarUrl the value for member_profile_log.avatar_url
     *
     * @mbggenerated
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile_log.mobile_code
     *
     * @return the value of member_profile_log.mobile_code
     *
     * @mbggenerated
     */
    public String getMobileCode() {
        return mobileCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile_log.mobile_code
     *
     * @param mobileCode the value for member_profile_log.mobile_code
     *
     * @mbggenerated
     */
    public void setMobileCode(String mobileCode) {
        this.mobileCode = mobileCode == null ? null : mobileCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile_log.mobile
     *
     * @return the value of member_profile_log.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile_log.mobile
     *
     * @param mobile the value for member_profile_log.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile_log.email
     *
     * @return the value of member_profile_log.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile_log.email
     *
     * @param email the value for member_profile_log.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile_log.description
     *
     * @return the value of member_profile_log.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile_log.description
     *
     * @param description the value for member_profile_log.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile_log.country
     *
     * @return the value of member_profile_log.country
     *
     * @mbggenerated
     */
    public Integer getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile_log.country
     *
     * @param country the value for member_profile_log.country
     *
     * @mbggenerated
     */
    public void setCountry(Integer country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile_log.province
     *
     * @return the value of member_profile_log.province
     *
     * @mbggenerated
     */
    public Integer getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile_log.province
     *
     * @param province the value for member_profile_log.province
     *
     * @mbggenerated
     */
    public void setProvince(Integer province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile_log.city
     *
     * @return the value of member_profile_log.city
     *
     * @mbggenerated
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile_log.city
     *
     * @param city the value for member_profile_log.city
     *
     * @mbggenerated
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile_log.district
     *
     * @return the value of member_profile_log.district
     *
     * @mbggenerated
     */
    public Integer getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile_log.district
     *
     * @param district the value for member_profile_log.district
     *
     * @mbggenerated
     */
    public void setDistrict(Integer district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile_log.address
     *
     * @return the value of member_profile_log.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile_log.address
     *
     * @param address the value for member_profile_log.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile_log.register_time
     *
     * @return the value of member_profile_log.register_time
     *
     * @mbggenerated
     */
    public Integer getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile_log.register_time
     *
     * @param registerTime the value for member_profile_log.register_time
     *
     * @mbggenerated
     */
    public void setRegisterTime(Integer registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile_log.update_time
     *
     * @return the value of member_profile_log.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile_log.update_time
     *
     * @param updateTime the value for member_profile_log.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }
}