package com.qf.withmycar.pojo;

public class MessageSendlog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_sendlog.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_sendlog.message_id
     *
     * @mbggenerated
     */
    private Long messageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_sendlog.send_time
     *
     * @mbggenerated
     */
    private Integer sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_sendlog.to_mid
     *
     * @mbggenerated
     */
    private Long toMid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_sendlog.received
     *
     * @mbggenerated
     */
    private Integer received;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_sendlog.receive_time
     *
     * @mbggenerated
     */
    private Integer receiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_sendlog.viewed
     *
     * @mbggenerated
     */
    private Byte viewed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_sendlog.view_time
     *
     * @mbggenerated
     */
    private Integer viewTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_sendlog.view_detail
     *
     * @mbggenerated
     */
    private Byte viewDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_sendlog.view_detail_time
     *
     * @mbggenerated
     */
    private Integer viewDetailTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_sendlog.id
     *
     * @return the value of message_sendlog.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_sendlog.id
     *
     * @param id the value for message_sendlog.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_sendlog.message_id
     *
     * @return the value of message_sendlog.message_id
     *
     * @mbggenerated
     */
    public Long getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_sendlog.message_id
     *
     * @param messageId the value for message_sendlog.message_id
     *
     * @mbggenerated
     */
    public void setMessageId(Long messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_sendlog.send_time
     *
     * @return the value of message_sendlog.send_time
     *
     * @mbggenerated
     */
    public Integer getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_sendlog.send_time
     *
     * @param sendTime the value for message_sendlog.send_time
     *
     * @mbggenerated
     */
    public void setSendTime(Integer sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_sendlog.to_mid
     *
     * @return the value of message_sendlog.to_mid
     *
     * @mbggenerated
     */
    public Long getToMid() {
        return toMid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_sendlog.to_mid
     *
     * @param toMid the value for message_sendlog.to_mid
     *
     * @mbggenerated
     */
    public void setToMid(Long toMid) {
        this.toMid = toMid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_sendlog.received
     *
     * @return the value of message_sendlog.received
     *
     * @mbggenerated
     */
    public Integer getReceived() {
        return received;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_sendlog.received
     *
     * @param received the value for message_sendlog.received
     *
     * @mbggenerated
     */
    public void setReceived(Integer received) {
        this.received = received;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_sendlog.receive_time
     *
     * @return the value of message_sendlog.receive_time
     *
     * @mbggenerated
     */
    public Integer getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_sendlog.receive_time
     *
     * @param receiveTime the value for message_sendlog.receive_time
     *
     * @mbggenerated
     */
    public void setReceiveTime(Integer receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_sendlog.viewed
     *
     * @return the value of message_sendlog.viewed
     *
     * @mbggenerated
     */
    public Byte getViewed() {
        return viewed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_sendlog.viewed
     *
     * @param viewed the value for message_sendlog.viewed
     *
     * @mbggenerated
     */
    public void setViewed(Byte viewed) {
        this.viewed = viewed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_sendlog.view_time
     *
     * @return the value of message_sendlog.view_time
     *
     * @mbggenerated
     */
    public Integer getViewTime() {
        return viewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_sendlog.view_time
     *
     * @param viewTime the value for message_sendlog.view_time
     *
     * @mbggenerated
     */
    public void setViewTime(Integer viewTime) {
        this.viewTime = viewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_sendlog.view_detail
     *
     * @return the value of message_sendlog.view_detail
     *
     * @mbggenerated
     */
    public Byte getViewDetail() {
        return viewDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_sendlog.view_detail
     *
     * @param viewDetail the value for message_sendlog.view_detail
     *
     * @mbggenerated
     */
    public void setViewDetail(Byte viewDetail) {
        this.viewDetail = viewDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_sendlog.view_detail_time
     *
     * @return the value of message_sendlog.view_detail_time
     *
     * @mbggenerated
     */
    public Integer getViewDetailTime() {
        return viewDetailTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_sendlog.view_detail_time
     *
     * @param viewDetailTime the value for message_sendlog.view_detail_time
     *
     * @mbggenerated
     */
    public void setViewDetailTime(Integer viewDetailTime) {
        this.viewDetailTime = viewDetailTime;
    }
}