package com.qf.withmycar.pojo;

public class SdkInterfaceType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface_type.type_id
     *
     * @mbggenerated
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface_type.interface_count
     *
     * @mbggenerated
     */
    private Integer interfaceCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface_type.id
     *
     * @return the value of sdk_interface_type.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface_type.id
     *
     * @param id the value for sdk_interface_type.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface_type.type_id
     *
     * @return the value of sdk_interface_type.type_id
     *
     * @mbggenerated
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface_type.type_id
     *
     * @param typeId the value for sdk_interface_type.type_id
     *
     * @mbggenerated
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface_type.interface_count
     *
     * @return the value of sdk_interface_type.interface_count
     *
     * @mbggenerated
     */
    public Integer getInterfaceCount() {
        return interfaceCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface_type.interface_count
     *
     * @param interfaceCount the value for sdk_interface_type.interface_count
     *
     * @mbggenerated
     */
    public void setInterfaceCount(Integer interfaceCount) {
        this.interfaceCount = interfaceCount;
    }
}