package com.qf.withmycar.pojo;

public class SdkInterfaceUdparm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface_udparm.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface_udparm.activity_id
     *
     * @mbggenerated
     */
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface_udparm.interface_id
     *
     * @mbggenerated
     */
    private Integer interfaceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface_udparm.namea
     *
     * @mbggenerated
     */
    private String namea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface_udparm.parm_name
     *
     * @mbggenerated
     */
    private String parmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface_udparm.data_type
     *
     * @mbggenerated
     */
    private Integer dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface_udparm.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface_udparm.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface_udparm.id
     *
     * @return the value of sdk_interface_udparm.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface_udparm.id
     *
     * @param id the value for sdk_interface_udparm.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface_udparm.activity_id
     *
     * @return the value of sdk_interface_udparm.activity_id
     *
     * @mbggenerated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface_udparm.activity_id
     *
     * @param activityId the value for sdk_interface_udparm.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface_udparm.interface_id
     *
     * @return the value of sdk_interface_udparm.interface_id
     *
     * @mbggenerated
     */
    public Integer getInterfaceId() {
        return interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface_udparm.interface_id
     *
     * @param interfaceId the value for sdk_interface_udparm.interface_id
     *
     * @mbggenerated
     */
    public void setInterfaceId(Integer interfaceId) {
        this.interfaceId = interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface_udparm.namea
     *
     * @return the value of sdk_interface_udparm.namea
     *
     * @mbggenerated
     */
    public String getNamea() {
        return namea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface_udparm.namea
     *
     * @param namea the value for sdk_interface_udparm.namea
     *
     * @mbggenerated
     */
    public void setNamea(String namea) {
        this.namea = namea == null ? null : namea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface_udparm.parm_name
     *
     * @return the value of sdk_interface_udparm.parm_name
     *
     * @mbggenerated
     */
    public String getParmName() {
        return parmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface_udparm.parm_name
     *
     * @param parmName the value for sdk_interface_udparm.parm_name
     *
     * @mbggenerated
     */
    public void setParmName(String parmName) {
        this.parmName = parmName == null ? null : parmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface_udparm.data_type
     *
     * @return the value of sdk_interface_udparm.data_type
     *
     * @mbggenerated
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface_udparm.data_type
     *
     * @param dataType the value for sdk_interface_udparm.data_type
     *
     * @mbggenerated
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface_udparm.description
     *
     * @return the value of sdk_interface_udparm.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface_udparm.description
     *
     * @param description the value for sdk_interface_udparm.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface_udparm.product_id
     *
     * @return the value of sdk_interface_udparm.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface_udparm.product_id
     *
     * @param productId the value for sdk_interface_udparm.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
}