package com.qf.withmycar.pojo;

public class SdkInterface {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface.type_id
     *
     * @mbggenerated
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface.desca
     *
     * @mbggenerated
     */
    private String desca;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface.success
     *
     * @mbggenerated
     */
    private String success;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface.error
     *
     * @mbggenerated
     */
    private String error;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface.request_type
     *
     * @mbggenerated
     */
    private String requestType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface.id
     *
     * @return the value of sdk_interface.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface.id
     *
     * @param id the value for sdk_interface.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface.type_id
     *
     * @return the value of sdk_interface.type_id
     *
     * @mbggenerated
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface.type_id
     *
     * @param typeId the value for sdk_interface.type_id
     *
     * @mbggenerated
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface.name
     *
     * @return the value of sdk_interface.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface.name
     *
     * @param name the value for sdk_interface.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface.desca
     *
     * @return the value of sdk_interface.desca
     *
     * @mbggenerated
     */
    public String getDesca() {
        return desca;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface.desca
     *
     * @param desca the value for sdk_interface.desca
     *
     * @mbggenerated
     */
    public void setDesca(String desca) {
        this.desca = desca == null ? null : desca.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface.url
     *
     * @return the value of sdk_interface.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface.url
     *
     * @param url the value for sdk_interface.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface.success
     *
     * @return the value of sdk_interface.success
     *
     * @mbggenerated
     */
    public String getSuccess() {
        return success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface.success
     *
     * @param success the value for sdk_interface.success
     *
     * @mbggenerated
     */
    public void setSuccess(String success) {
        this.success = success == null ? null : success.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface.error
     *
     * @return the value of sdk_interface.error
     *
     * @mbggenerated
     */
    public String getError() {
        return error;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface.error
     *
     * @param error the value for sdk_interface.error
     *
     * @mbggenerated
     */
    public void setError(String error) {
        this.error = error == null ? null : error.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface.request_type
     *
     * @return the value of sdk_interface.request_type
     *
     * @mbggenerated
     */
    public String getRequestType() {
        return requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface.request_type
     *
     * @param requestType the value for sdk_interface.request_type
     *
     * @mbggenerated
     */
    public void setRequestType(String requestType) {
        this.requestType = requestType == null ? null : requestType.trim();
    }
}