package com.qf.withmycar.pojo;

public class Visitor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.visitor_guid
     *
     * @mbggenerated
     */
    private String visitorGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.first_visit_time
     *
     * @mbggenerated
     */
    private Integer firstVisitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.entry_url
     *
     * @mbggenerated
     */
    private String entryUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.visitor_ip
     *
     * @mbggenerated
     */
    private String visitorIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.visitor_device
     *
     * @mbggenerated
     */
    private String visitorDevice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.visitor_channel
     *
     * @mbggenerated
     */
    private String visitorChannel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.id
     *
     * @return the value of visitor.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.id
     *
     * @param id the value for visitor.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.visitor_guid
     *
     * @return the value of visitor.visitor_guid
     *
     * @mbggenerated
     */
    public String getVisitorGuid() {
        return visitorGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.visitor_guid
     *
     * @param visitorGuid the value for visitor.visitor_guid
     *
     * @mbggenerated
     */
    public void setVisitorGuid(String visitorGuid) {
        this.visitorGuid = visitorGuid == null ? null : visitorGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.first_visit_time
     *
     * @return the value of visitor.first_visit_time
     *
     * @mbggenerated
     */
    public Integer getFirstVisitTime() {
        return firstVisitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.first_visit_time
     *
     * @param firstVisitTime the value for visitor.first_visit_time
     *
     * @mbggenerated
     */
    public void setFirstVisitTime(Integer firstVisitTime) {
        this.firstVisitTime = firstVisitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.entry_url
     *
     * @return the value of visitor.entry_url
     *
     * @mbggenerated
     */
    public String getEntryUrl() {
        return entryUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.entry_url
     *
     * @param entryUrl the value for visitor.entry_url
     *
     * @mbggenerated
     */
    public void setEntryUrl(String entryUrl) {
        this.entryUrl = entryUrl == null ? null : entryUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.visitor_ip
     *
     * @return the value of visitor.visitor_ip
     *
     * @mbggenerated
     */
    public String getVisitorIp() {
        return visitorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.visitor_ip
     *
     * @param visitorIp the value for visitor.visitor_ip
     *
     * @mbggenerated
     */
    public void setVisitorIp(String visitorIp) {
        this.visitorIp = visitorIp == null ? null : visitorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.visitor_device
     *
     * @return the value of visitor.visitor_device
     *
     * @mbggenerated
     */
    public String getVisitorDevice() {
        return visitorDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.visitor_device
     *
     * @param visitorDevice the value for visitor.visitor_device
     *
     * @mbggenerated
     */
    public void setVisitorDevice(String visitorDevice) {
        this.visitorDevice = visitorDevice == null ? null : visitorDevice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.visitor_channel
     *
     * @return the value of visitor.visitor_channel
     *
     * @mbggenerated
     */
    public String getVisitorChannel() {
        return visitorChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.visitor_channel
     *
     * @param visitorChannel the value for visitor.visitor_channel
     *
     * @mbggenerated
     */
    public void setVisitorChannel(String visitorChannel) {
        this.visitorChannel = visitorChannel == null ? null : visitorChannel.trim();
    }
}