package com.qf.withmycar.pojo;

public class ArticleAction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_action.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_action.article_id
     *
     * @mbggenerated
     */
    private Long articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_action.operator_uid
     *
     * @mbggenerated
     */
    private Integer operatorUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_action.operator_username
     *
     * @mbggenerated
     */
    private String operatorUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_action.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_action.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_action.operate_type
     *
     * @mbggenerated
     */
    private Byte operateType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_action.id
     *
     * @return the value of article_action.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_action.id
     *
     * @param id the value for article_action.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_action.article_id
     *
     * @return the value of article_action.article_id
     *
     * @mbggenerated
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_action.article_id
     *
     * @param articleId the value for article_action.article_id
     *
     * @mbggenerated
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_action.operator_uid
     *
     * @return the value of article_action.operator_uid
     *
     * @mbggenerated
     */
    public Integer getOperatorUid() {
        return operatorUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_action.operator_uid
     *
     * @param operatorUid the value for article_action.operator_uid
     *
     * @mbggenerated
     */
    public void setOperatorUid(Integer operatorUid) {
        this.operatorUid = operatorUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_action.operator_username
     *
     * @return the value of article_action.operator_username
     *
     * @mbggenerated
     */
    public String getOperatorUsername() {
        return operatorUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_action.operator_username
     *
     * @param operatorUsername the value for article_action.operator_username
     *
     * @mbggenerated
     */
    public void setOperatorUsername(String operatorUsername) {
        this.operatorUsername = operatorUsername == null ? null : operatorUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_action.create_time
     *
     * @return the value of article_action.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_action.create_time
     *
     * @param createTime the value for article_action.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_action.content
     *
     * @return the value of article_action.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_action.content
     *
     * @param content the value for article_action.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_action.operate_type
     *
     * @return the value of article_action.operate_type
     *
     * @mbggenerated
     */
    public Byte getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_action.operate_type
     *
     * @param operateType the value for article_action.operate_type
     *
     * @mbggenerated
     */
    public void setOperateType(Byte operateType) {
        this.operateType = operateType;
    }
}