package com.qf.withmycar.pojo;

import java.util.Date;

public class CarBrand {
    private Integer id;
    private String namea;
    private String otherName;
    private String englishName;
    private Integer countryId;
    private String logoUrl;
    private String logoMeaning;
    private String firstChar;
    private String spell;
    private String allSpell;
    private String nameSpell;
    private String nameAllSpell;
    private String introduction;
    private Byte saleStatus;
    private Byte isEnabled;
    private Byte isRemoved;
    private Date createTime;
    private Date updateTime;
    private Date doTime;
    private Date syncTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.id
     *
     * @return the value of car_brand.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.id
     *
     * @param id the value for car_brand.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.namea
     *
     * @return the value of car_brand.namea
     *
     * @mbggenerated
     */
    public String getNamea() {
        return namea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.namea
     *
     * @param namea the value for car_brand.namea
     *
     * @mbggenerated
     */
    public void setNamea(String namea) {
        this.namea = namea == null ? null : namea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.other_name
     *
     * @return the value of car_brand.other_name
     *
     * @mbggenerated
     */
    public String getOtherName() {
        return otherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.other_name
     *
     * @param otherName the value for car_brand.other_name
     *
     * @mbggenerated
     */
    public void setOtherName(String otherName) {
        this.otherName = otherName == null ? null : otherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.english_name
     *
     * @return the value of car_brand.english_name
     *
     * @mbggenerated
     */
    public String getEnglishName() {
        return englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.english_name
     *
     * @param englishName the value for car_brand.english_name
     *
     * @mbggenerated
     */
    public void setEnglishName(String englishName) {
        this.englishName = englishName == null ? null : englishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.country_id
     *
     * @return the value of car_brand.country_id
     *
     * @mbggenerated
     */
    public Integer getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.country_id
     *
     * @param countryId the value for car_brand.country_id
     *
     * @mbggenerated
     */
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.logo_url
     *
     * @return the value of car_brand.logo_url
     *
     * @mbggenerated
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.logo_url
     *
     * @param logoUrl the value for car_brand.logo_url
     *
     * @mbggenerated
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl == null ? null : logoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.logo_meaning
     *
     * @return the value of car_brand.logo_meaning
     *
     * @mbggenerated
     */
    public String getLogoMeaning() {
        return logoMeaning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.logo_meaning
     *
     * @param logoMeaning the value for car_brand.logo_meaning
     *
     * @mbggenerated
     */
    public void setLogoMeaning(String logoMeaning) {
        this.logoMeaning = logoMeaning == null ? null : logoMeaning.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.first_char
     *
     * @return the value of car_brand.first_char
     *
     * @mbggenerated
     */
    public String getFirstChar() {
        return firstChar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.first_char
     *
     * @param firstChar the value for car_brand.first_char
     *
     * @mbggenerated
     */
    public void setFirstChar(String firstChar) {
        this.firstChar = firstChar == null ? null : firstChar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.spell
     *
     * @return the value of car_brand.spell
     *
     * @mbggenerated
     */
    public String getSpell() {
        return spell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.spell
     *
     * @param spell the value for car_brand.spell
     *
     * @mbggenerated
     */
    public void setSpell(String spell) {
        this.spell = spell == null ? null : spell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.all_spell
     *
     * @return the value of car_brand.all_spell
     *
     * @mbggenerated
     */
    public String getAllSpell() {
        return allSpell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.all_spell
     *
     * @param allSpell the value for car_brand.all_spell
     *
     * @mbggenerated
     */
    public void setAllSpell(String allSpell) {
        this.allSpell = allSpell == null ? null : allSpell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.name_spell
     *
     * @return the value of car_brand.name_spell
     *
     * @mbggenerated
     */
    public String getNameSpell() {
        return nameSpell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.name_spell
     *
     * @param nameSpell the value for car_brand.name_spell
     *
     * @mbggenerated
     */
    public void setNameSpell(String nameSpell) {
        this.nameSpell = nameSpell == null ? null : nameSpell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.name_all_spell
     *
     * @return the value of car_brand.name_all_spell
     *
     * @mbggenerated
     */
    public String getNameAllSpell() {
        return nameAllSpell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.name_all_spell
     *
     * @param nameAllSpell the value for car_brand.name_all_spell
     *
     * @mbggenerated
     */
    public void setNameAllSpell(String nameAllSpell) {
        this.nameAllSpell = nameAllSpell == null ? null : nameAllSpell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.introduction
     *
     * @return the value of car_brand.introduction
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.introduction
     *
     * @param introduction the value for car_brand.introduction
     *
     * @mbggenerated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.sale_status
     *
     * @return the value of car_brand.sale_status
     *
     * @mbggenerated
     */
    public Byte getSaleStatus() {
        return saleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.sale_status
     *
     * @param saleStatus the value for car_brand.sale_status
     *
     * @mbggenerated
     */
    public void setSaleStatus(Byte saleStatus) {
        this.saleStatus = saleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.is_enabled
     *
     * @return the value of car_brand.is_enabled
     *
     * @mbggenerated
     */
    public Byte getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.is_enabled
     *
     * @param isEnabled the value for car_brand.is_enabled
     *
     * @mbggenerated
     */
    public void setIsEnabled(Byte isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_brand.is_removed
     *
     * @return the value of car_brand.is_removed
     *
     * @mbggenerated
     */
    public Byte getIsRemoved() {
        return isRemoved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_brand.is_removed
     *
     * @param isRemoved the value for car_brand.is_removed
     *
     * @mbggenerated
     */
    public void setIsRemoved(Byte isRemoved) {
        this.isRemoved = isRemoved;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Date getDoTime() {
        return doTime;
    }

    public void setDoTime(Date doTime) {
        this.doTime = doTime;
    }

    public Date getSyncTime() {
        return syncTime;
    }

    public void setSyncTime(Date syncTime) {
        this.syncTime = syncTime;
    }

    @Override
    public String toString() {
        return "CarBrand{" +
                "id=" + id +
                ", namea='" + namea + '\'' +
                ", otherName='" + otherName + '\'' +
                ", englishName='" + englishName + '\'' +
                ", countryId=" + countryId +
                ", logoUrl='" + logoUrl + '\'' +
                ", logoMeaning='" + logoMeaning + '\'' +
                ", firstChar='" + firstChar + '\'' +
                ", spell='" + spell + '\'' +
                ", allSpell='" + allSpell + '\'' +
                ", nameSpell='" + nameSpell + '\'' +
                ", nameAllSpell='" + nameAllSpell + '\'' +
                ", introduction='" + introduction + '\'' +
                ", saleStatus=" + saleStatus +
                ", isEnabled=" + isEnabled +
                ", isRemoved=" + isRemoved +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                ", doTime=" + doTime +
                ", syncTime=" + syncTime +
                '}';
    }
}