package com.qf.withmycar.pojo;

public class CarModelImage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model_image.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model_image.model_id
     *
     * @mbggenerated
     */
    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model_image.year
     *
     * @mbggenerated
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model_image.defaults
     *
     * @mbggenerated
     */
    private Integer defaults;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model_image.img_url
     *
     * @mbggenerated
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model_image.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model_image.update_time
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_model_image.sync_time
     *
     * @mbggenerated
     */
    private Integer syncTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model_image.id
     *
     * @return the value of car_model_image.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model_image.id
     *
     * @param id the value for car_model_image.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model_image.model_id
     *
     * @return the value of car_model_image.model_id
     *
     * @mbggenerated
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model_image.model_id
     *
     * @param modelId the value for car_model_image.model_id
     *
     * @mbggenerated
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model_image.year
     *
     * @return the value of car_model_image.year
     *
     * @mbggenerated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model_image.year
     *
     * @param year the value for car_model_image.year
     *
     * @mbggenerated
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model_image.defaults
     *
     * @return the value of car_model_image.defaults
     *
     * @mbggenerated
     */
    public Integer getDefaults() {
        return defaults;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model_image.defaults
     *
     * @param defaults the value for car_model_image.defaults
     *
     * @mbggenerated
     */
    public void setDefaults(Integer defaults) {
        this.defaults = defaults;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model_image.img_url
     *
     * @return the value of car_model_image.img_url
     *
     * @mbggenerated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model_image.img_url
     *
     * @param imgUrl the value for car_model_image.img_url
     *
     * @mbggenerated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model_image.create_time
     *
     * @return the value of car_model_image.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model_image.create_time
     *
     * @param createTime the value for car_model_image.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model_image.update_time
     *
     * @return the value of car_model_image.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model_image.update_time
     *
     * @param updateTime the value for car_model_image.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_model_image.sync_time
     *
     * @return the value of car_model_image.sync_time
     *
     * @mbggenerated
     */
    public Integer getSyncTime() {
        return syncTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_model_image.sync_time
     *
     * @param syncTime the value for car_model_image.sync_time
     *
     * @mbggenerated
     */
    public void setSyncTime(Integer syncTime) {
        this.syncTime = syncTime;
    }
}