package com.qf.withmycar.pojo;

import java.util.Objects;

public class CarParam {
    private Integer paramid;
    private String paramname;//参数名
    private String paramstate;//参数状态
    private String parambase;//是否为基础参数

    @Override
    public String toString() {
        return "CarParam{" +
                "paramid=" + paramid +
                ", paramname='" + paramname + '\'' +
                ", paramstate='" + paramstate + '\'' +
                ", parambase='" + parambase + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_param.paramid
     *
     * @return the value of car_param.paramid
     *
     * @mbggenerated
     */
    public Integer getParamid() {
        return paramid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_param.paramid
     *
     * @param paramid the value for car_param.paramid
     *
     * @mbggenerated
     */
    public void setParamid(Integer paramid) {
        this.paramid = paramid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_param.paramname
     *
     * @return the value of car_param.paramname
     *
     * @mbggenerated
     */
    public String getParamname() {
        return paramname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_param.paramname
     *
     * @param paramname the value for car_param.paramname
     *
     * @mbggenerated
     */
    public void setParamname(String paramname) {
        this.paramname = paramname == null ? null : paramname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_param.paramstate
     *
     * @return the value of car_param.paramstate
     *
     * @mbggenerated
     */
    public String getParamstate() {
        return paramstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_param.paramstate
     *
     * @param paramstate the value for car_param.paramstate
     *
     * @mbggenerated
     */
    public void setParamstate(String paramstate) {
        this.paramstate = paramstate == null ? null : paramstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_param.parambase
     *
     * @return the value of car_param.parambase
     *
     * @mbggenerated
     */
    public String getParambase() {
        return parambase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_param.parambase
     *
     * @param parambase the value for car_param.parambase
     *
     * @mbggenerated
     */
    public void setParambase(String parambase) {
        this.parambase = parambase == null ? null : parambase.trim();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        CarParam carParam = (CarParam) o;
        return Objects.equals(paramid, carParam.paramid) &&
                Objects.equals(paramname, carParam.paramname) &&
                Objects.equals(paramstate, carParam.paramstate) &&
                Objects.equals(parambase, carParam.parambase);
    }

    @Override
    public int hashCode() {
        return Objects.hash(paramid, paramname, paramstate, parambase);
    }
}