package com.qf.withmycar.pojo;

import java.math.BigDecimal;

public class CarSelectList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_select_list.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_select_list.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_select_list.country
     *
     * @mbggenerated
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_select_list.car_type
     *
     * @mbggenerated
     */
    private String carType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_select_list.car_type_bak
     *
     * @mbggenerated
     */
    private Boolean carTypeBak;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_select_list.msrp_min
     *
     * @mbggenerated
     */
    private BigDecimal msrpMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_select_list.msrp_max
     *
     * @mbggenerated
     */
    private BigDecimal msrpMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_select_list.country_type
     *
     * @mbggenerated
     */
    private Boolean countryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_select_list.country_std
     *
     * @mbggenerated
     */
    private Boolean countryStd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_select_list.space_std
     *
     * @mbggenerated
     */
    private BigDecimal spaceStd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_select_list.power_std
     *
     * @mbggenerated
     */
    private BigDecimal powerStd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_select_list.comfort_std
     *
     * @mbggenerated
     */
    private BigDecimal comfortStd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_select_list.cost_std
     *
     * @mbggenerated
     */
    private BigDecimal costStd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_select_list.safe_std
     *
     * @mbggenerated
     */
    private BigDecimal safeStd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_select_list.car_id
     *
     * @mbggenerated
     */
    private Integer carId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_select_list.id
     *
     * @return the value of car_select_list.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_select_list.id
     *
     * @param id the value for car_select_list.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_select_list.type
     *
     * @return the value of car_select_list.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_select_list.type
     *
     * @param type the value for car_select_list.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_select_list.country
     *
     * @return the value of car_select_list.country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_select_list.country
     *
     * @param country the value for car_select_list.country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_select_list.car_type
     *
     * @return the value of car_select_list.car_type
     *
     * @mbggenerated
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_select_list.car_type
     *
     * @param carType the value for car_select_list.car_type
     *
     * @mbggenerated
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_select_list.car_type_bak
     *
     * @return the value of car_select_list.car_type_bak
     *
     * @mbggenerated
     */
    public Boolean getCarTypeBak() {
        return carTypeBak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_select_list.car_type_bak
     *
     * @param carTypeBak the value for car_select_list.car_type_bak
     *
     * @mbggenerated
     */
    public void setCarTypeBak(Boolean carTypeBak) {
        this.carTypeBak = carTypeBak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_select_list.msrp_min
     *
     * @return the value of car_select_list.msrp_min
     *
     * @mbggenerated
     */
    public BigDecimal getMsrpMin() {
        return msrpMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_select_list.msrp_min
     *
     * @param msrpMin the value for car_select_list.msrp_min
     *
     * @mbggenerated
     */
    public void setMsrpMin(BigDecimal msrpMin) {
        this.msrpMin = msrpMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_select_list.msrp_max
     *
     * @return the value of car_select_list.msrp_max
     *
     * @mbggenerated
     */
    public BigDecimal getMsrpMax() {
        return msrpMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_select_list.msrp_max
     *
     * @param msrpMax the value for car_select_list.msrp_max
     *
     * @mbggenerated
     */
    public void setMsrpMax(BigDecimal msrpMax) {
        this.msrpMax = msrpMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_select_list.country_type
     *
     * @return the value of car_select_list.country_type
     *
     * @mbggenerated
     */
    public Boolean getCountryType() {
        return countryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_select_list.country_type
     *
     * @param countryType the value for car_select_list.country_type
     *
     * @mbggenerated
     */
    public void setCountryType(Boolean countryType) {
        this.countryType = countryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_select_list.country_std
     *
     * @return the value of car_select_list.country_std
     *
     * @mbggenerated
     */
    public Boolean getCountryStd() {
        return countryStd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_select_list.country_std
     *
     * @param countryStd the value for car_select_list.country_std
     *
     * @mbggenerated
     */
    public void setCountryStd(Boolean countryStd) {
        this.countryStd = countryStd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_select_list.space_std
     *
     * @return the value of car_select_list.space_std
     *
     * @mbggenerated
     */
    public BigDecimal getSpaceStd() {
        return spaceStd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_select_list.space_std
     *
     * @param spaceStd the value for car_select_list.space_std
     *
     * @mbggenerated
     */
    public void setSpaceStd(BigDecimal spaceStd) {
        this.spaceStd = spaceStd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_select_list.power_std
     *
     * @return the value of car_select_list.power_std
     *
     * @mbggenerated
     */
    public BigDecimal getPowerStd() {
        return powerStd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_select_list.power_std
     *
     * @param powerStd the value for car_select_list.power_std
     *
     * @mbggenerated
     */
    public void setPowerStd(BigDecimal powerStd) {
        this.powerStd = powerStd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_select_list.comfort_std
     *
     * @return the value of car_select_list.comfort_std
     *
     * @mbggenerated
     */
    public BigDecimal getComfortStd() {
        return comfortStd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_select_list.comfort_std
     *
     * @param comfortStd the value for car_select_list.comfort_std
     *
     * @mbggenerated
     */
    public void setComfortStd(BigDecimal comfortStd) {
        this.comfortStd = comfortStd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_select_list.cost_std
     *
     * @return the value of car_select_list.cost_std
     *
     * @mbggenerated
     */
    public BigDecimal getCostStd() {
        return costStd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_select_list.cost_std
     *
     * @param costStd the value for car_select_list.cost_std
     *
     * @mbggenerated
     */
    public void setCostStd(BigDecimal costStd) {
        this.costStd = costStd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_select_list.safe_std
     *
     * @return the value of car_select_list.safe_std
     *
     * @mbggenerated
     */
    public BigDecimal getSafeStd() {
        return safeStd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_select_list.safe_std
     *
     * @param safeStd the value for car_select_list.safe_std
     *
     * @mbggenerated
     */
    public void setSafeStd(BigDecimal safeStd) {
        this.safeStd = safeStd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_select_list.car_id
     *
     * @return the value of car_select_list.car_id
     *
     * @mbggenerated
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_select_list.car_id
     *
     * @param carId the value for car_select_list.car_id
     *
     * @mbggenerated
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }
}