package com.qf.withmycar.pojo;

public class DictModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_model.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_model.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_model.country
     *
     * @mbggenerated
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_model.model_name
     *
     * @mbggenerated
     */
    private String modelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_model.model_id
     *
     * @mbggenerated
     */
    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_model.msrp_min
     *
     * @mbggenerated
     */
    private Integer msrpMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_model.space
     *
     * @mbggenerated
     */
    private Byte space;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_model.power
     *
     * @mbggenerated
     */
    private Byte power;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_model.comfort
     *
     * @mbggenerated
     */
    private Byte comfort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_model.cost
     *
     * @mbggenerated
     */
    private Byte cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_model.safety
     *
     * @mbggenerated
     */
    private Byte safety;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_model.id
     *
     * @return the value of dict_model.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_model.id
     *
     * @param id the value for dict_model.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_model.code
     *
     * @return the value of dict_model.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_model.code
     *
     * @param code the value for dict_model.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_model.country
     *
     * @return the value of dict_model.country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_model.country
     *
     * @param country the value for dict_model.country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_model.model_name
     *
     * @return the value of dict_model.model_name
     *
     * @mbggenerated
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_model.model_name
     *
     * @param modelName the value for dict_model.model_name
     *
     * @mbggenerated
     */
    public void setModelName(String modelName) {
        this.modelName = modelName == null ? null : modelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_model.model_id
     *
     * @return the value of dict_model.model_id
     *
     * @mbggenerated
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_model.model_id
     *
     * @param modelId the value for dict_model.model_id
     *
     * @mbggenerated
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_model.msrp_min
     *
     * @return the value of dict_model.msrp_min
     *
     * @mbggenerated
     */
    public Integer getMsrpMin() {
        return msrpMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_model.msrp_min
     *
     * @param msrpMin the value for dict_model.msrp_min
     *
     * @mbggenerated
     */
    public void setMsrpMin(Integer msrpMin) {
        this.msrpMin = msrpMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_model.space
     *
     * @return the value of dict_model.space
     *
     * @mbggenerated
     */
    public Byte getSpace() {
        return space;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_model.space
     *
     * @param space the value for dict_model.space
     *
     * @mbggenerated
     */
    public void setSpace(Byte space) {
        this.space = space;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_model.power
     *
     * @return the value of dict_model.power
     *
     * @mbggenerated
     */
    public Byte getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_model.power
     *
     * @param power the value for dict_model.power
     *
     * @mbggenerated
     */
    public void setPower(Byte power) {
        this.power = power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_model.comfort
     *
     * @return the value of dict_model.comfort
     *
     * @mbggenerated
     */
    public Byte getComfort() {
        return comfort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_model.comfort
     *
     * @param comfort the value for dict_model.comfort
     *
     * @mbggenerated
     */
    public void setComfort(Byte comfort) {
        this.comfort = comfort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_model.cost
     *
     * @return the value of dict_model.cost
     *
     * @mbggenerated
     */
    public Byte getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_model.cost
     *
     * @param cost the value for dict_model.cost
     *
     * @mbggenerated
     */
    public void setCost(Byte cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_model.safety
     *
     * @return the value of dict_model.safety
     *
     * @mbggenerated
     */
    public Byte getSafety() {
        return safety;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_model.safety
     *
     * @param safety the value for dict_model.safety
     *
     * @mbggenerated
     */
    public void setSafety(Byte safety) {
        this.safety = safety;
    }
}