package com.qf.withmycar.pojo;

public class DictBrandPoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_brand_point.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_brand_point.brand_id
     *
     * @mbggenerated
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_brand_point.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_brand_point.point
     *
     * @mbggenerated
     */
    private Byte point;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_brand_point.id
     *
     * @return the value of dict_brand_point.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_brand_point.id
     *
     * @param id the value for dict_brand_point.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_brand_point.brand_id
     *
     * @return the value of dict_brand_point.brand_id
     *
     * @mbggenerated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_brand_point.brand_id
     *
     * @param brandId the value for dict_brand_point.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_brand_point.name
     *
     * @return the value of dict_brand_point.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_brand_point.name
     *
     * @param name the value for dict_brand_point.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_brand_point.point
     *
     * @return the value of dict_brand_point.point
     *
     * @mbggenerated
     */
    public Byte getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_brand_point.point
     *
     * @param point the value for dict_brand_point.point
     *
     * @mbggenerated
     */
    public void setPoint(Byte point) {
        this.point = point;
    }
}