package com.qf.withmycar.pojo;

public class ProductCarActivity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_car_activity.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_car_activity.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_car_activity.car_id
     *
     * @mbggenerated
     */
    private Integer carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_car_activity.activity_id
     *
     * @mbggenerated
     */
    private Integer activityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_car_activity.id
     *
     * @return the value of product_car_activity.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_car_activity.id
     *
     * @param id the value for product_car_activity.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_car_activity.product_id
     *
     * @return the value of product_car_activity.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_car_activity.product_id
     *
     * @param productId the value for product_car_activity.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_car_activity.car_id
     *
     * @return the value of product_car_activity.car_id
     *
     * @mbggenerated
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_car_activity.car_id
     *
     * @param carId the value for product_car_activity.car_id
     *
     * @mbggenerated
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_car_activity.activity_id
     *
     * @return the value of product_car_activity.activity_id
     *
     * @mbggenerated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_car_activity.activity_id
     *
     * @param activityId the value for product_car_activity.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }
}