package com.qf.withmycar.pojo;

public class SdkInterfaceParm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface_parm.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface_parm.interface_id
     *
     * @mbggenerated
     */
    private Integer interfaceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface_parm.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface_parm.parm_name
     *
     * @mbggenerated
     */
    private String parmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface_parm.data_type
     *
     * @mbggenerated
     */
    private Integer dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface_parm.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface_parm.is_required
     *
     * @mbggenerated
     */
    private Integer isRequired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface_parm.is_custom
     *
     * @mbggenerated
     */
    private Integer isCustom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface_parm.is_login
     *
     * @mbggenerated
     */
    private Integer isLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_interface_parm.activity_key
     *
     * @mbggenerated
     */
    private Integer activityKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface_parm.id
     *
     * @return the value of sdk_interface_parm.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface_parm.id
     *
     * @param id the value for sdk_interface_parm.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface_parm.interface_id
     *
     * @return the value of sdk_interface_parm.interface_id
     *
     * @mbggenerated
     */
    public Integer getInterfaceId() {
        return interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface_parm.interface_id
     *
     * @param interfaceId the value for sdk_interface_parm.interface_id
     *
     * @mbggenerated
     */
    public void setInterfaceId(Integer interfaceId) {
        this.interfaceId = interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface_parm.name
     *
     * @return the value of sdk_interface_parm.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface_parm.name
     *
     * @param name the value for sdk_interface_parm.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface_parm.parm_name
     *
     * @return the value of sdk_interface_parm.parm_name
     *
     * @mbggenerated
     */
    public String getParmName() {
        return parmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface_parm.parm_name
     *
     * @param parmName the value for sdk_interface_parm.parm_name
     *
     * @mbggenerated
     */
    public void setParmName(String parmName) {
        this.parmName = parmName == null ? null : parmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface_parm.data_type
     *
     * @return the value of sdk_interface_parm.data_type
     *
     * @mbggenerated
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface_parm.data_type
     *
     * @param dataType the value for sdk_interface_parm.data_type
     *
     * @mbggenerated
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface_parm.description
     *
     * @return the value of sdk_interface_parm.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface_parm.description
     *
     * @param description the value for sdk_interface_parm.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface_parm.is_required
     *
     * @return the value of sdk_interface_parm.is_required
     *
     * @mbggenerated
     */
    public Integer getIsRequired() {
        return isRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface_parm.is_required
     *
     * @param isRequired the value for sdk_interface_parm.is_required
     *
     * @mbggenerated
     */
    public void setIsRequired(Integer isRequired) {
        this.isRequired = isRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface_parm.is_custom
     *
     * @return the value of sdk_interface_parm.is_custom
     *
     * @mbggenerated
     */
    public Integer getIsCustom() {
        return isCustom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface_parm.is_custom
     *
     * @param isCustom the value for sdk_interface_parm.is_custom
     *
     * @mbggenerated
     */
    public void setIsCustom(Integer isCustom) {
        this.isCustom = isCustom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface_parm.is_login
     *
     * @return the value of sdk_interface_parm.is_login
     *
     * @mbggenerated
     */
    public Integer getIsLogin() {
        return isLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface_parm.is_login
     *
     * @param isLogin the value for sdk_interface_parm.is_login
     *
     * @mbggenerated
     */
    public void setIsLogin(Integer isLogin) {
        this.isLogin = isLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_interface_parm.activity_key
     *
     * @return the value of sdk_interface_parm.activity_key
     *
     * @mbggenerated
     */
    public Integer getActivityKey() {
        return activityKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_interface_parm.activity_key
     *
     * @param activityKey the value for sdk_interface_parm.activity_key
     *
     * @mbggenerated
     */
    public void setActivityKey(Integer activityKey) {
        this.activityKey = activityKey;
    }
}