package com.qf.withmycar.pojo;

public class SdkTemp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_temp.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_temp.activity_id
     *
     * @mbggenerated
     */
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_temp.sdk_path
     *
     * @mbggenerated
     */
    private String sdkPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_temp.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdk_temp.sdk_name
     *
     * @mbggenerated
     */
    private String sdkName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_temp.id
     *
     * @return the value of sdk_temp.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_temp.id
     *
     * @param id the value for sdk_temp.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_temp.activity_id
     *
     * @return the value of sdk_temp.activity_id
     *
     * @mbggenerated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_temp.activity_id
     *
     * @param activityId the value for sdk_temp.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_temp.sdk_path
     *
     * @return the value of sdk_temp.sdk_path
     *
     * @mbggenerated
     */
    public String getSdkPath() {
        return sdkPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_temp.sdk_path
     *
     * @param sdkPath the value for sdk_temp.sdk_path
     *
     * @mbggenerated
     */
    public void setSdkPath(String sdkPath) {
        this.sdkPath = sdkPath == null ? null : sdkPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_temp.create_time
     *
     * @return the value of sdk_temp.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_temp.create_time
     *
     * @param createTime the value for sdk_temp.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdk_temp.sdk_name
     *
     * @return the value of sdk_temp.sdk_name
     *
     * @mbggenerated
     */
    public String getSdkName() {
        return sdkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdk_temp.sdk_name
     *
     * @param sdkName the value for sdk_temp.sdk_name
     *
     * @mbggenerated
     */
    public void setSdkName(String sdkName) {
        this.sdkName = sdkName == null ? null : sdkName.trim();
    }
}