package com.qf.withmycar.pojo;

public class VisitLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_log.visitor_id
     *
     * @mbggenerated
     */
    private Long visitorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_log.member_id
     *
     * @mbggenerated
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_log.visit_url
     *
     * @mbggenerated
     */
    private String visitUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_log.visit_ip
     *
     * @mbggenerated
     */
    private String visitIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_log.visit_device
     *
     * @mbggenerated
     */
    private String visitDevice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_log.visit_source
     *
     * @mbggenerated
     */
    private String visitSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_log.enter_time
     *
     * @mbggenerated
     */
    private Integer enterTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_log.exit_time
     *
     * @mbggenerated
     */
    private Integer exitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_log.stay
     *
     * @mbggenerated
     */
    private Integer stay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_log.id
     *
     * @return the value of visit_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_log.id
     *
     * @param id the value for visit_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_log.visitor_id
     *
     * @return the value of visit_log.visitor_id
     *
     * @mbggenerated
     */
    public Long getVisitorId() {
        return visitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_log.visitor_id
     *
     * @param visitorId the value for visit_log.visitor_id
     *
     * @mbggenerated
     */
    public void setVisitorId(Long visitorId) {
        this.visitorId = visitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_log.member_id
     *
     * @return the value of visit_log.member_id
     *
     * @mbggenerated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_log.member_id
     *
     * @param memberId the value for visit_log.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_log.visit_url
     *
     * @return the value of visit_log.visit_url
     *
     * @mbggenerated
     */
    public String getVisitUrl() {
        return visitUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_log.visit_url
     *
     * @param visitUrl the value for visit_log.visit_url
     *
     * @mbggenerated
     */
    public void setVisitUrl(String visitUrl) {
        this.visitUrl = visitUrl == null ? null : visitUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_log.visit_ip
     *
     * @return the value of visit_log.visit_ip
     *
     * @mbggenerated
     */
    public String getVisitIp() {
        return visitIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_log.visit_ip
     *
     * @param visitIp the value for visit_log.visit_ip
     *
     * @mbggenerated
     */
    public void setVisitIp(String visitIp) {
        this.visitIp = visitIp == null ? null : visitIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_log.visit_device
     *
     * @return the value of visit_log.visit_device
     *
     * @mbggenerated
     */
    public String getVisitDevice() {
        return visitDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_log.visit_device
     *
     * @param visitDevice the value for visit_log.visit_device
     *
     * @mbggenerated
     */
    public void setVisitDevice(String visitDevice) {
        this.visitDevice = visitDevice == null ? null : visitDevice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_log.visit_source
     *
     * @return the value of visit_log.visit_source
     *
     * @mbggenerated
     */
    public String getVisitSource() {
        return visitSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_log.visit_source
     *
     * @param visitSource the value for visit_log.visit_source
     *
     * @mbggenerated
     */
    public void setVisitSource(String visitSource) {
        this.visitSource = visitSource == null ? null : visitSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_log.enter_time
     *
     * @return the value of visit_log.enter_time
     *
     * @mbggenerated
     */
    public Integer getEnterTime() {
        return enterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_log.enter_time
     *
     * @param enterTime the value for visit_log.enter_time
     *
     * @mbggenerated
     */
    public void setEnterTime(Integer enterTime) {
        this.enterTime = enterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_log.exit_time
     *
     * @return the value of visit_log.exit_time
     *
     * @mbggenerated
     */
    public Integer getExitTime() {
        return exitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_log.exit_time
     *
     * @param exitTime the value for visit_log.exit_time
     *
     * @mbggenerated
     */
    public void setExitTime(Integer exitTime) {
        this.exitTime = exitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_log.stay
     *
     * @return the value of visit_log.stay
     *
     * @mbggenerated
     */
    public Integer getStay() {
        return stay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_log.stay
     *
     * @param stay the value for visit_log.stay
     *
     * @mbggenerated
     */
    public void setStay(Integer stay) {
        this.stay = stay;
    }
}